### ISSUE TITLE
JavaDocs for UpdateTurnList Inaccurate

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_java_suite#1017]
### Bug Report
The JavaDocs for a softbutton array inside of UpdateTurnList reference a max value of 4, however the mobile api has a max value of 1.  When time permits the documentation should be updated as error can be seen in guides.
Snippet below:
```
    /**
     * Sets the SoftButtons
     * 
     * @param softButtons
     *            a List<SoftButton> value
     *            <p>
     *            <b>Notes: </b></p>
     *            <ul>
     *            <li>If omitted on supported displays, the alert will not have any SoftButton</li>
     *            <li>ArrayMin: 0</li>
     *            <li>ArrayMax: 4</li>
     *            </ul>
     * @since SmartDeviceLink 2.0
     */

    public void setSoftButtons(List<SoftButton> softButtons){
        setParameters(KEY_SOFT_BUTTONS, softButtons);
    }
```
JavaDocs:
https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/proxy/rpc/UpdateTurnList.java#L88

Mobile API:
https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L5841

##### Reproduction Steps
Review JavaDocs for UpdateTurnList and compare to mobile api

##### Expected Behavior
Accurate JavaDocs

##### Observed Behavior
Incorrect JavaDocs

**Comment by joeygrover** [comment]
Confirmed the RPC spec defines it as the same : https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L5841

Very strange definition for a param, an array with max value 1. However, issue is valid; I will get it fixed for this RC.

Just an FYI, the RPC spec reference should be used over the Core MOBILE_API.xml as the "source of truth".

**Comment by joeygrover** [comment]
Will be fixed with commit: https://github.com/smartdevicelink/sdl_android/pull/1015/commits/730ae6c8538c33bea4aa718a1e16244f398b899b
