### ISSUE TITLE
AudioStreamManager is missing function for sending audio buffer

### ISSUE THREAD

**Issue by ed-h** [smartdevicelink/sdl_java_suite#1042]
### Bug Report
Currently `AudioStreamManager` only provides `pushAudioSource` for sending Uri for audio buffer. It should provides a function such as `pushAudioBuffer(ByteBuffer bytes)`.
It will be useful for navigation app as audio are generated as byte buffer instead of actual files.

##### Reproduction Steps
1. Create a navigation app and get `AudioStreamManager` from `SdlManager`.
2. As `IAudioStreamListener sdlAudioStream` is private, it is not possible to call `sendAudio` 

##### Expected Behavior
AudioStreamManager should provide function to pushAudioBuffer

##### OS & Version Information
* Android Version: 8.0/9.0
* SDL Android Version: SDL 4.7.2/4.8.0 RC4

**Comment by BrettyWhite** [comment]
Hi @ed-h,

We actually have this scoped for a future update. Unfortunately it won't be a part of 4.8 which is slated to be released in the next few days. We will keep track of this and be sure to expand the Audio Stream Manager's functionality in the future. 

Feel free to reach out to us on slack as well http://slack.smartdevicelink.com

Thanks

**Comment by BrettyWhite** [comment]
Closed with #1087

**Comment by ed-h** [comment]
@BrettyWhite 

I see the AudioManager only provides startAudioStream(boolean encrypted, final CompletionListener completionListener);

Is it possible to add startAudioStream(boolean encrypted, (boolean encrypted, final AudioStreamingCodec codec, final AudioStreamingParams params, final CompletionListener completionListener)?

So the app can specify the audio streaming parameters for the audio buffer. I am hoping this can make into the 4.9.0 release so we can switch to the new SdlManager method.

Thanks

**Comment by bilal-alsharifi** [comment]
Hi @ed-h 4.9 is scheduled to be released after 2 days so I don't think that can be added to 4.9. I also believe the sdl_android chooses the best configurations that are supported by the head unit automatically so passing params will not make a difference. You can always add [evolution proposal](https://github.com/smartdevicelink/sdl_evolution) to change the behavior or suggest adding new features.

**Comment by ed-h** [comment]
@bilal-alsharifi 
The head unit I am using requires us to set AudioStreamingCodec to 44100 in order to play the tts properly, without specifying the AudioSteamingCodec, I cannot hear anything on the head unit.

Since this is a very simple modification, I have attached the patch file here. Thanks

[audiomanager_patch.txt](https://github.com/smartdevicelink/sdl_java_suite/files/3332782/audiomanager_patch.txt)

**Comment by ed-h** [comment]
I have re-tested the function of AudioStreamManager on the head unit, and the current function seems to be working, please ignore previous comment. Thanks
