### ISSUE TITLE
Number of notifications

### ISSUE THREAD

**Issue by FayaX-PT** [smartdevicelink/sdl_java_suite#1044]
Hello,

I would like to know if it is normal to see 2 notifications of the same application regarding SDL.
I have installed the hello SDL application in your documentation (https://smartdevicelink.com/en/guides/android/getting-started/hello-sdl-android/) and when the app is connected to the car, 2 notifications are visible. Althouth, the FordPass app only shows one notification (see screenshot below)

##### OS & Version Information
* Android Version: 9

![57313535_322456975137266_4340477443778281472_n](https://user-images.githubusercontent.com/9136651/56302520-d963d100-6131-11e9-8fe6-d4745afbab12.jpg)

**Comment by joeygrover** [comment]
This is normal. They are two different notifications. One for the transport connection that works for all apps. The other is for the specific apps and their services.

**Comment by alves-Dr** [comment]
Hello @joeygrover,
In that case, how can Ford bypass this situation by having only one notification?

thanks,
Diogo

**Comment by joeygrover** [comment]
Per the previous comment, it is using the transport service that the other app has started. Only one transport service is necessary for all apps.

**Comment by FayaX-PT** [comment]
But if I uninstall the demo application, and only stay with the FordPass app I only see one notification.
![57155630_1665985473546711_7044712823275913216_n (1)](https://user-images.githubusercontent.com/9136651/56304698-9bb57700-6136-11e9-84c8-540ae572c325.jpg)

**Comment by joeygrover** [comment]
Their implementation is likely incorrect then. There is no way to properly get around the transport service notification.
