### ISSUE TITLE
Difficult to import sdl_android as source library

### ISSUE THREAD

**Issue by yimsunAmazon** [smartdevicelink/sdl_java_suite#1048]
### Bug Report
This is not a bug. Rather, we would like to share some feedback regarding the new source code structure introduced in SDL 4.8.0 for java_suite/Android.  We prefer to import the SDL Android library in source code form into our build system, rather than using it as a pre-built aar, but the new code structure makes it laborious and error-prone to bring in the SDL android source tree.  Since the `base` module is a mixed bag of source files for both android and non-android, we have to walk through all leaf-level directories, and copy only the files and directories from `base` that are symlinked in `baseAndroid` into `sdl_android`.  

If we missed a file/directory, or copied over an extra file, it would fail to compile. And that is actually a good thing because compilation errors tell us something was amiss.  What we fear the most are these namesake files in both `sdl_android` and `base` -- that if we accidentally overwrote one of these files from `base`, but it somehow still compiled, our code would be running with unintended logic.

Therefore we are wondering if you could help ease the friction by either providing some tools/scripts for extracting and merging into a single sdl_android source library without symlinks, or, restructuring the code by breaking down `base` further into 3 modules:  `android-only`,  `non-android-only`, and `common-for-all`, all without any symlinks, so we can merge at the root directory level?

Thanks!

**Comment by joeygrover** [comment]
Hi @yimsunAmazon 

Hopefully we can assist you in making the project work for your use case. The library itself can be used either as the distributed library or source so we will have to understand why it isn't working for you. 

First some insight into the changes. The recent release of the project itself is structured in a very specific way. The android base folder with symbolic links is a temporary bridge; the common files were all written with the future implementation in mind, so there are a few breaking changes that we couldn't include in the Android library without bumping to a major version change. Therefore, we created the symbolic link source set. That folder contains all common files that the Android project uses. You can check the build.gradle file for the SDL Android library and see it is the only added source set; so the only files the android lib needs are the ones that are symbolically linked in that source set. Once the next major version of the library is distributed, the symbolic links in that folder will no longer be necessary. For now, we didn't want to create folder structures that would need larger overhauls or maintenance instead opting for a straight forward design with minimal footprint. 

So a few questions I have for you to help us assist you. 

- Are there any specific reasons you choose to import the library as source vs the distributed library?
- Are you using Android Studio as your IDE?
- Or at least the Gradle Android Build System?

**Comment by yimsunAmazon** [comment]
Hi Joey,

Thank you for the explanation. I just want to clarify that we did manage to get the source library imported, just it was more laborious and error-prone than importing the previous versions, and thus the feedback for we didn't know if this would be the norm from now on.

Importing source code form rather than distributed binary is due to several reasons, including security policy, smaller footprints on source repository, ease in patching and  troubleshooting.

So it sounds like the use of symlinks is just a temporary solution and future releases of the SDL library will have a better structure. We really look forward to that.

**Comment by joeygrover** [comment]
Just as a quick follow up. In case you are using the gradle build system it will be easy to import the cloned source now and even in the future when the symbolic link folder is removed. We will only be changing the build script for the sdl_android project not changing its location. So the android/sdl_android/build.gradle will handle the the redirection. 

So adding the additional layer to the `setting.gradle` as followed will work for now and when we remove the baseAndroid folder.

From: 
 `project (":sdl_android").projectDir = new File("[Root File System]/sdl_android_project/sdl_android")`

To: 
 `project (":sdl_android").projectDir = new File("[Root File System]/sdl_android_project/android/sdl_android")`

**Comment by theresalech** [comment]
Closed via #1442
