### ISSUE TITLE
SDL_UNAVAILABLE response code and missing RPC references

### ISSUE THREAD

**Issue by yimsunAmazon** [smartdevicelink/sdl_java_suite#1049]
### Bug Report
While troubleshooting for an issue we encountered after upgrading Android SDL to v4.7.2, we saw one RPC call returned SDL_UNAVAILABLE status code in our log.  We used to be able to look it up from the smartdevicelink.com website's RPC reference section to have some idea of what it means, but that section seems to have been removed.

We would like to request that RPC reference section to be added back to the documentation site as it would benefit developers like us.  Some of us may be still using older versions of SDL library/API, and even for those have upgraded to the new Manager APIs, having references to what's under the hood is still valuable for debugging and troubleshooting.

Thanks.

**Comment by joeygrover** [comment]
Hi @yimsunAmazon 

There is currently an issue with the way our developer portal builds the documentation from source; we are actively addressing the issue and should have a fix coming. However, that documentation is built off the javadoc inline documentation that is in the actual source code. Therefore, all that documentation is still available through the library distribution itself for the time being. We apologize for the inconvenience.

**Comment by yimsunAmazon** [comment]
Thanks for the quick response, Joey, and we really appreciate it.  It is good to know that the missing documentation is only due to a javaDoc generation issue and is not permanently removed. I will search for the doc in the source code itself.
