### ISSUE TITLE
I can't get the value by getPressureTellTale()

### ISSUE THREAD

**Issue by jianglin2018** [smartdevicelink/sdl_java_suite#1057]
### Bug Report
Null is returned to the phone side when the phone side wishes to obtain the PressureTellTale value by getPressureTellTale().
Because the KEY_PRESSURE_TELL_TALE definition in SDL Core is wrong.
The KEY_PRESSURE_TELL_TALE  should be  changed from "pressureTellTale" to "pressureTelltale"

TireStatus.java line104
public static final String KEY_PRESSURE_TELL_TALE = "pressureTellTale";

**Comment by bilal-alsharifi** [comment]
Thanks for reporting the issue. The key value in Android should be changed from `pressureTellTale` to `pressureTelltale` to match what is in Core and the [RPC Specs](https://github.com/smartdevicelink/rpc_spec). We will issue a fix for that.
