### ISSUE TITLE
`sendSequentialRPCs` doesn't call `onResponse` and stops on first `onError`

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_java_suite#1061]
##### Reproduction Steps
1. Create a list of RPCs where one is for sure invalid
2. call sdlManager.sendSequentialRPCs and set a completion handler overriding all methods
3. observe handler method calls

##### Expected Behavior
1. All RPCs should be sent one after the other
2. `OnMultipleRequestListener.onResponse` should be called to **all** RPCs regardless of success. This is very important on unsuccessful subscribing to vehicle data
3. `OnMultipleRequestListener.onError` should be called for the unsuccessful request. The error should not interrupt the sequential operation.
4. `onResponse` listener set into the RPC should be called

##### Observed Behavior
1. `OnMultipleRequestListener.onResponse` is never called.
2. Requests are not sent after first error
3. `onResponse` listener set into the RPC is overriden by the manager

##### OS & Version Information
* Android Version: Any
* SDL Android Version: 4.8
* Testing Against: hello_sdl_android

**Comment by theresalech** [comment]
Closed via #1066
