### ISSUE TITLE
New Router Service and old USB Transport compatibility issues

### ISSUE THREAD

**Issue by khburdette** [smartdevicelink/sdl_java_suite#1064]
### Bug Report
The new router service design has conflicts with the older USB transport

##### Reproduction Steps
Install (from the play store): App Catalog and Sygic Car Navigation
Install Hello SDL with 4.8.1 library version

Scenario 1:
* Plug in device
* Select Hello SDL on the AOA popup:
  * observed behavior: App Catalog and Hello SDL show up on the head unit

Scenario 2:
* Plug in device
* Select Sygic on the AOA popup:
  * observed behavior: Sygic shows up, Hello SDL has foreground service but never shows up
  * when you unplug the device, Hello SDL never removed it's foreground notification, so this is putting Hello SDL into a bad state where it can't register again over bluetooth

##### Expected Behavior
Hello SDL, App Catalog and Sygic all show up no matter what app you select in the AOA popup

##### Observed Behavior
See above. Different behavior depending on which app you select on the AOA popup

##### OS & Version Information
* Android Version: 9
* SDL Android Version: 4.8.1
* Testing Against: SYNC 3

**Comment by joeygrover** [comment]
Please note, if apps are not updated to at least SDL Android lib 4.7, they will not have access to the multi app AOA connection through the router service. There is nothing we can do about this.  They simply do not have the transport code that will allow them to connect through the router service for AOA or supply the router service with the AOA connection.

**Comment by joeygrover** [comment]
#1065 should address the issue that hello SDL shows up when an older library uses the original AOA connection. The other issues are not possible to be worked around; we have to work with partners to ensure they update their apps.

**Comment by BrettyWhite** [comment]
Closed with #1065
