### ISSUE TITLE
[SDL 0232] Add Pushing Buffer Support to AudioStreamManager

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1075]
Proposal: [Add Pushing Buffer Support to AudioStreamManager](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0232-add_pushing_buffer_support_to_audio_stream_manager.md)

> This proposal is to add the ability to push an audio buffer to the `AudioStreamManager` so it supports playing audio from raw data in addition to supporting playing audio from actual files.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/732

**Comment by ed-h** [comment]
I see the AudioManager only provides startAudioStream(boolean encrypted, final CompletionListener completionListener);

Is it possible to add startAudioStream(boolean encrypted, (boolean encrypted, final AudioStreamingCodec codec, final AudioStreamingParams params, final CompletionListener completionListener)? 

So the app can specify the audio streaming parameters for the audio buffer.

Thanks
