### ISSUE TITLE
LeftRearInflatableBelted using wrong key value in BeltStatus Class

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_java_suite#1078]
### Bug Report

The LeftRearInflatableBelted getter and setter methods are using wrong key value in BeltStatus Class resulting in a null value always being returned from getter method.

Parameter is named leftRearInflatableBelted in RPC spec:
https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L1539-L1541

Parameter is erroneously using rearInflatableBelted as the key in java suite:

https://github.com/smartdevicelink/sdl_java_suite/blob/80d6737382c43dff10358198b5a4cccf3b802cfc/base/src/main/java/com/smartdevicelink/proxy/rpc/BeltStatus.java#L269-L274

https://github.com/smartdevicelink/sdl_java_suite/blob/80d6737382c43dff10358198b5a4cccf3b802cfc/base/src/main/java/com/smartdevicelink/proxy/rpc/BeltStatus.java#L163-L164

##### Reproduction Steps
Utilize the get vehicle data api and attempt to return belt status, take note the value is always null.  Also review the above and take note that an incorrect key is being used to acquire the data.

##### Expected Behavior
The getLeftRearInflatableBelted method for the belt status class returns the correct data.

##### Observed Behavior
The getLeftRearInflatableBelted method for the belt status class always returns null because of an incorrect key.

##### OS & Version Information
* Android Version: Android Pie
SDL Android Version: 4.8.1
Testing Against: TDK with proprietary HMI

**Comment by BrettyWhite** [comment]
Closed with #1084
