### ISSUE TITLE
[SDL 0220] Support for Android custom RouterService

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1079]
Proposal: [Support for Android custom RouterService](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0220-support-for-android-custom-routerservice.md)

> This proposal is to improve the case where SDL applications need to work with custom RouterService. A custom RouterService refers to the RouterService that does not use the open source's RouterService code. The app that contains custom RouterService must indicate the flag in its AndroidManifest.xml. This proposal refers to the case where an OEM-specific head unit requires an OEM-specific app to work as the RouterService. For instance, if an OEM uses a specific Bluetooth server UUID that differs from SDL standard ones, that should be a custom RouterService.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/691

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the revision included in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/691#issuecomment-494454220)

> The proposal .md file was updated to reflect these revisions on 5/28/19.

**Comment by E-SAITO-TMC** [comment]
Will this PR be included in the next release (2020 1Q)?
What is a blocker?

**Comment by joeygrover** [comment]
This was not scheduled for 4.10.0 release so the PR was not reviewed. If prioritized by the SDLC this can be included in 4.11.0 release.

**Comment by E-SAITO-TMC** [comment]
@joeygrover 
Thank you for replay.
That's great!
Please consider including in 4.11.
