### ISSUE TITLE
_priorHmiLevel and _priorAudioStreamingState are never set

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_java_suite#108]
When the [SdlProxyBase class receives an onHmiStatus notification](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java#L2223) it appears that the intention is to notify the developer only [if the hmi and(??) audio states have changed](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java#L2237).

If this is the case, then there is a bug because `_priorHmiLevel` and `_priorAudioStreamingState` are never set by SdlProxyBase - what is currently happening is just a null check for those parameters.

If this is just supposed to be a null check then the code should be changed because it is not very readable. If it is supposed to notify the developer of a state change then the if statement should be composed with an _or_ and the prior states should be tracked.

**Comment by justinjdickow** [comment]
Updated link to the logic I'm talking about: https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java#L2274-L2284

**Comment by bilal-alsharifi** [comment]
Closed for being stale.
