### ISSUE TITLE
NPE in TransportBrokerImpl.onHardwareDisconnected(SourceFile_309)

### ISSUE THREAD

**Issue by yingchun1** [smartdevicelink/sdl_java_suite#1082]
### Bug Report
[NPE in TransportBrokerImpl.onHardwareDisconnected(SourceFile_309)]

Whole trace is:
java.lang.NullPointerException_ Attempt to invoke virtual method 'com.smartdevicelink.transport.enums.TransportType com.smartdevicelink.transport.utl.TransportRecord.getType()' on a null object reference at com.smartdevicelink.transport.TransportManager$TransportBrokerImpl.onHardwareDisconnected(SourceFile_309) at com.smartdevicelink.transport.TransportBroker$1.onServiceDisconnected(SourceFile_124) at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java_1858) at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java_1873) at android.os.Handler.handleCallback(Handler.java_873) at android.os.Handler.dispatchMessage(Handler.java_99) at android.os.Looper.loop(Looper.java_214) at android.app.ActivityThread.main(ActivityThread.java_6981) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java_493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java_1445)

##### OS & Version Information
* Android Version: Android 8.0
* SDL Android Version: 4.8.0

**Comment by theresalech** [comment]
Closed via #1105
