### ISSUE TITLE
NPE in UsbAccessory.getManufacturer()

### ISSUE THREAD

**Issue by AndrewKasilov** [smartdevicelink/sdl_java_suite#1086]
### Bug Report
`
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.usb.UsbAccessory.getManufacturer()' on a null object reference at com.smartdevicelink.transport.USBTransport.isAccessorySupported(USBTransport.java:534)
`
##### Reproduction Steps
1. Start `USBAccessoryAttachmentActivity` 
2. Call method `wakeUpRouterService()`, there should be only legacy connection possible
3. Immediately finish the `USBAccessoryAttachmentActivity`

##### Expected Behavior
Broadcast is not sent with `usbAccessory == null`

##### Observed Behavior
When `USBAccessoryAttachmentActivity` is destroyed before the broadcast is sent,
`usbAccessory` is set to `null` in `onDestroy` and then is sent in the broadcast.

##### OS & Version Information
* Android Version: 8.1
* SDL Android Version: 4.8.0

**Comment by joeygrover** [comment]
Closed as a result of https://github.com/smartdevicelink/sdl_evolution/pull/628

**Comment by BrettyWhite** [comment]
Closed with #1177
