### ISSUE TITLE
Android X support

### ISSUE THREAD

**Issue by BugsBunnyBR** [smartdevicelink/sdl_java_suite#1094]
Any plans to support android X?

**Comment by joeygrover** [comment]
Eventually, yes. We still have to do an analysis to see if it will be breaking change for the public API or not.

**Comment by BugsBunnyBR** [comment]
Even if it does not break the public API the dependencies, like `com.android.support:support-annotation` are still bundled in the app, making it bigger, which is not good for our users.

**Comment by theresalech** [comment]
Closed via #1441
