### ISSUE TITLE
Not able to start SdlManager 2nd time with TCPTransportConfig

### ISSUE THREAD

**Issue by ed-h** [smartdevicelink/sdl_java_suite#1097]
### Bug Report
We are creating an app that uses Wi-Fi for SDL, during testing, we found out that SdlManager will fail to start on the first time.

##### Reproduction Steps
1. SdlService is started, and use TCPTransportConfig to start SdlManager, SdlManagerListener::onStart will be called.
2. Stop the service manually, and mSdlManager.dispose() is called to make sure SdlManager is cleaned up.
3. Start SdlService again, and use TCPTransportConfig to start SdlManager on the same IP address for the 2nd time, SdlManagerListener's onStart will not be called, not even onError.

##### Expected Behavior
SdlManager should be able to started the second time.

##### Observed Behavior
SdlManager is not able to start on the 2nd time with TCPTransportConfig

##### OS & Version Information
* Android Version: 8.0/9.0
* SDL Android Version: 4.8.1/4.9.0 RC

**Comment by bilal-alsharifi** [comment]
Could you please check if the service is stopped correctly by printing a log message in `SdlService.onDestroy()`? I would also print a log message right before `sdlManager.start()` to make sure that the manager gets started the second time.
It is worth mentioning as well that the TCP transport is for debugging purposes only. It is not meant to be used in a production app.

**Comment by ed-h** [comment]
Hi bilal-alsharifi

I am sure the SdlService onDestroy is called when I tried to stop SDLServicec. (I can also see the service foreground notification is gone). I can also confirm the SdlManagerListener's onDestroy being called.

And yes, I can see the sdlManager.start() getting called on the 2nd time, but it will never go to SdlManagerListener's onStart, not even onError.

**Comment by bilal-alsharifi** [comment]
Hi @ed-h 

Can you please also confirm that a new instance of `SdlManager` is created the second time?. `SdlManager` instance cannot be reused after disposal. 
You can also enable the debugging tool by running `DebugTool.enableDebugTool()` in the entry point to your app and check if you see any error logs in logcat. Posting the logs here will be helpful as well.

**Comment by ed-h** [comment]
@bilal-alsharifi  sorry for the late response as I was away.
Yes, I can confirm the new instance of SdlManager is created on the second time.

Will TCPTransport's disconnect function gets called when calling SdlManager is disposed?
From the log below, I have called dispose around 17:30, but it seems TCPTransport is still connected, and switching to DISCONNECTING in 17:39:47.

> `06-25 17:29:31.887 27369 27500 I com.smartdevicelink.transport.TCPTransport: TCPTransport: sendBytesOverTransport request accepted. Trying to send data
06-25 17:29:31.887 27369 27500 I com.smartdevicelink.transport.TCPTransport: TCPTransport.sendBytesOverTransport: successfully send data
06-25 17:29:31.890 27369 27500 I com.smartdevicelink.transport.TCPTransport: TCPTransport: sendBytesOverTransport requested. Size: 58, Offset: 0, Length: 58, Current state is: CONNECTED
06-25 17:29:31.890 27369 27500 I com.smartdevicelink.transport.TCPTransport: TCPTransport: sendBytesOverTransport request accepted. Trying to send data
06-25 17:29:31.890 27369 27500 I com.smartdevicelink.transport.TCPTransport: TCPTransport.sendBytesOverTransport: successfully send data
06-25 17:39:47.260 27369 27501 E com.smartdevicelink.transport.TCPTransport: TCPTransport.run: Exception during reading data
06-25 17:39:47.271 27369 27501 I com.smartdevicelink.transport.TCPTransport: Current state changed to: DISCONNECTING
06-25 17:39:47.273 27369 27501 E com.smartdevicelink.transport.TCPTransport: Disconnect is incorrect. Handling it as error
06-25 17:39:47.274 27369 27501 E SdlProxy: 	at com.smartdevicelink.transport.TCPTransport$TCPTransportThread.internalHandleStreamReadError(TCPTransport.java:489)
06-25 17:39:47.274 27369 27501 E SdlProxy: 	at com.smartdevicelink.transport.TCPTransport$TCPTransportThread.run(TCPTransport.java:430)
06-25 17:39:47.278 27369 27501 I com.smartdevicelink.transport.TCPTransport: TCPTransport: openConnection requested. Current state is: IDLE`





Also Here is some logs after calling start() on the 2nd SdlManager

> 06-25 16:14:33.064 22590 22590 I SdlProxy: SDL_LIB_VERSION: 4.8.1
06-25 16:14:33.070 22590 22590 I com.smartdevicelink.transport.TCPTransport: TCPTransport: sendBytesOverTransport requested. Size: 44, Offset: 0, Length: 44, Current state is: CONNECTED
06-25 16:14:33.070 22590 22590 I com.smartdevicelink.transport.TCPTransport: TCPTransport: sendBytesOverTransport request accepted. Trying to send data
06-25 16:14:33.070 22590 22590 E com.smartdevicelink.transport.TCPTransport: TCPTransport.sendBytesOverTransport: error during sending data: null

**Comment by bilal-alsharifi** [comment]
Hi @ed-h , thanks for providing more details. We will investigate the issue but this is going to have a lower priority because TCP transport is used for debugging purposes only and it is not meant to be used in production.

**Comment by theresalech** [comment]
@ed-h can you please test with the latest version of the library and let us know if you're still experiencing this issue?

**Comment by bilal-alsharifi** [comment]
This PR #1108 refactors the TCP transport to follow the newer stack and it seems that it solves the aforementioned issue as well.
