### ISSUE TITLE
SoftButtonObject should let developers set their own ids

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1126]
Currently, the `SoftButtonManager` assigns ids automatically to the `SoftButtons` before sending them. If the developer sets id using `SoftbuttonObject.setButtonId()`, the id value set by the developer will simply be ignored because the manager will assign a new one. This behavior is confusing. The `SoftButtonManager` shouldn't override the ids set by the developer.

**Comment by BrettyWhite** [comment]
Closed via #1131
