### ISSUE TITLE
[SDL 0230] SPP resource management for Android

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1132]
Proposal: [SPP resource management for Android](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0230-spp-resource-management-for-android.md)

> RFCOMM is a connection-oriented, streaming transport over Bluetooth, which is known as Serial Port Profile (SPP) in Android. SDL Proxy uses BluetoothServerSocket to listen on a SPP channel, and it is used for primary transport. On an Android device, the number of SPP resources is limited, and BluetoothServerSocket fails to accept connections when SPP channel runs out of available resources. Current SDL Proxy does not handle that case very well. This proposal is to improve the SPP resource management in SDL Android.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/730

Steering Committee Decision:

>During the Steering Committee discussion of this issue, it was noted that the Steering Committee had previously considered the possibility of pointing the user to a URL/Webpage with regards to the `SDLNotificationActivity` component, and came to the conclusion that a notification with "Too many apps are using Bluetooth" dialog would be best as to not overcomplicate the UX and take advantage of the Android system's internationalization.  Additional information about this item can be found in the review issue comments.

It was also specified that by accepting the proposal, members understood that the notification implemented by the feature will be "noisy" including lights, vibration, and sound.  Additionally, the notification will display the following message to the user "Too many apps are using Bluetooth" (in English).  It was understood by members that the English string would be accepted by accepting the proposal, and there would be an additional review period for SDLC Members to review translations of this string.

Ultimately, the proposal was accepted with the revisions included in the author's comment [here](https://github.com/smartdevicelink/sdl_evolution/issues/730#issuecomment-514008710).

> The proposal .md file was updated to reflect these revisions on 7/25/19.

**Comment by E-SAITO-TMC** [comment]
When will this proposal be released?

**Comment by theresalech** [comment]
@E-SAITO-TMC, this feature has not yet been raised as priority by the Steering Committee.  If this is priority for Toyota, please let us know, and we can work to include in the next Java Suite release (planned for July).  Thank you!
