### ISSUE TITLE
ChoiceSetManager fails if VR is not optional

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1137]
### Bug Report
`ChoiceSetManager` currently switches to `ERROR` state if VR optional test fails.

https://github.com/smartdevicelink/sdl_java_suite/blob/df717f0c198fedef5f6f16ab7db2aaee04d4d97b/base/src/main/java/com/smartdevicelink/managers/screen/choiceset/CheckChoiceVROptionalOperation.java#L92

The correct behavior should be that VR should be considered not optional and the manager should switch to state `READY` instead of failing. 

##### Reproduction Steps
1. Test presenting a choice set with a head unit that requires VR in choices (Sync 3 emulator for example)
2. Note that choices are not presented 

##### Expected Behavior
Choices should be presented 

##### Observed Behavior
Choices are not presented

##### OS & Version Information
* Android Version: 9.0
* SDL Android Version: 4.9
* Testing Against: Sync 3 emulator .

**Comment by theresalech** [comment]
Closed via #1139
