### ISSUE TITLE
Extract from XML and decode Logcat messages

### ISSUE THREAD

**Issue by PKramchaninov** [smartdevicelink/sdl_java_suite#115]
Currently if writing message to Syphon fails native Android log is used.  Messages which are passed to native logger are encoded and wrapped in xml and thus are often unreadable. This makes difficult to get logging information for those who don't use Syphon.

I'd like to propose a small change which will extract log message form xml and decode it before logging.

**Comment by mikeburke106** [comment]
I think there might be a way to receive the logs prior to them being converted to XML in [SdlTrace](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java), but I'm not too familiar with the siphon server and the current logging approach, so either @Heath-FoMoCo  or @mrapitis will have to fill in the blanks here.

We have a broader discussion around logging in #51 and we may come up with a different logging solution via LogCat or 3rd party API in the future.

**Comment by PKramchaninov** [comment]
Indeed in my implementation I forced to extract and decode message after it was already converted and encoded. This approach may cause minor performance overhead but it requires minimum changes thus maybe it could be accepted as a temporary solution while different logging solution is still in progress.

I can suggest three options:
1. Temporary apply implementation which encode/decode convert/extract overhead.
2. Introduce different implementation which will solve issue and won't contain overhead.
3. Introduce completely new logging implementation.

I could provide a pull-request for option 1 and 2 and I could contribute in for option 3.

**Comment by mikeburke106** [comment]
Awesome, feel free to make any changes you think would be helpful and we'll review it.  Make sure to follow the [contributor guidelines](https://github.com/smartdevicelink/sdl_android/blob/master/CONTRIBUTING.md) when creating the PR.
