### ISSUE TITLE
Interrupted Exception during ProxyMessageDispatcher queuing

### ISSUE THREAD

**Issue by atiwari9** [smartdevicelink/sdl_java_suite#1198]
### Bug Report
Interrupted Exception during `ProxyMessageDispatcher` queuing

##### Reproduction Steps
1. Start an Automation test with AutoTester app with multiple RPC tests

##### Expected Behavior
RPC request should be sent and received to/from headunit w/o any errors.

##### Observed Behavior

```
10-07 15:25:15.124 30977 31073 E AutoTester: ******onProxyError******Exception encountered when queueing message.
10-07 15:25:15.124 30977 31073 I AutoTester: ******onProxyError******Exception encountered when queueing message.

10-07 15:25:15.130 30977 31073 E AutoTester: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1244)
10-07 15:25:15.130 30977 31073 E AutoTester: 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:336)
10-07 15:25:15.130 30977 31073 E AutoTester: 	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
10-07 15:25:15.130 30977 31073 E AutoTester: 	at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher.queueMessage(ProxyMessageDispatcher.java:87)
10-07 15:25:15.130 30977 31073 E AutoTester: 	at com.smartdevicelink.proxy.SdlProxyBase.sendRPCMessagePrivate(SdlProxyBase.java:2182)
10-07 15:25:15.130 30977 31073 E AutoTester: 	at com.smartdevicelink.proxy.SdlProxyBase.sendRPC(SdlProxyBase.java:4528)
10-07 15:25:15.130 30977 31073 E AutoTester: 	at com.smartdevicelink.proxy.SdlProxyBase.sendRPCRequest(SdlProxyBase.java:4540)
10-07 15:25:15.130 30977 31073 E AutoTester: 	at com.ford.syncV4.android.autotester.module.ModuleTest$7.run(ModuleTest.java:3262)
10-07 15:25:15.130 30977 31073 E AutoTester: 	at java.lang.Thread.run(Thread.java:764)
```
* Similar issue is also seen during incoming message handler
```
 ******onProxyError******Error handing incoming protocol message 
INFO: Date-03:32:51 9860Base:OnAudioPassThru (notification) - null
INFO: ******onProxyError******Error serializing message.”
```

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: SdlProxy: SDL_LIB_VERSION: 4.9.1
* Testing Against: SYNC 3/4 Headunit DEV SW

##### Test Case, Sample Code, and / or Example App
App: AutoTester(https://rink.hockeyapp.net/apps/de0f9d8c05e5006c1e8671fa8782e1c1)
TestXML: 
[PerformAudioPassThru.xml.txt](https://github.com/smartdevicelink/sdl_java_suite/files/3725350/PerformAudioPassThru.xml.txt)
(This is just a sample xml file which can be used with AutoTester app. Change the extension to .xml before using it with app)
Logs: 
[Logs for OnProxyError - APT.zip](https://github.com/smartdevicelink/sdl_java_suite/files/3725362/Logs.for.OnProxyError.-.APT.zip)

##### Occurrence:
About 5-10% , this issue is seen during regression tests which tests through various RPCs. So the issue is not limited to one particular test case or RPC, It just happens randomly.

**Comment by joeygrover** [comment]
Can you please provide reproduction steps that don't involve a proprietary app?

**Comment by atiwari9** [comment]
@joeygrover - Sure, Steps are basic RPC communication. Our automation test suite sends RPCs and performs some actions on HeadUnit like button presses, app startup/transition which would trigger some `onHMIStatus` updates as well. But i am fairly confident that this issue would be visible even without any HMI action. 

Important step to reproduce this issue is to prolong app(RPCs request/response) usage to about 2-3 hours with a mix of RPCs. 

This issue does have an occurrence of about 5-10 % and occurs randomly. So I understand that it can be a little tricky to identify the issue, but we can run the tests as per specific steps which might help isolate the issue for you. Do you have any recommendations on that?

**Comment by joeygrover** [comment]
@atiwari9 I'm looking for as specific of reproduction steps as possible. We test of basic RPC communication. Most tests will involved sending RPCs so this is not something we've seen in normal usage and testing environments.

I would ask that you put yourself in our shoes here; the only info we have is it occurs 5-10% of time after sending RPCs for 2-3 hours. The best approach to get this investigated and fixed is to help identify reproduction steps, that way it is more likely that we can identify what's causing the issue because we can actually see the issue occur. As we haven't seen the issue, you will have to work through what makes it happen and then work backwards to understand what your steps were to get there.

**Comment by atiwari9** [comment]
@joeygrover - I haven't been able to reproduce this issue with _Hello_SDL_ app. We can close this issue for now.

**Comment by joeygrover** [comment]
Thanks for the update! If you run across this again and have the specific reproduction steps we can open it back up and take a look.
