### ISSUE TITLE
Vehicle Data classes are not scalable

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_java_suite#12]
There are currently 25 supported vehicle data types with demand to add even more in the future.

However, current vehicle data RPC classes contain a distinct setter/getter method for each individual vehicle data type - which means each RPC related to vehicle data needs to define 50 separate methods.  As we add more vehicle data types, 2 additional methods (a setter & getter) will need to be added to each RPC.

A better way would be to define all vehicle data types in an enum and provide a generic hash map that maps the vehicle data enum to it's associated object (depends on the specific RPC in question).  In this design, adding a new type of vehicle data only requires that it be added to the enum.

**Comment by joeljfischer** [comment]
Closing due to updates
