### ISSUE TITLE
[SDL 0253] New vehicle data StabilityControlsStatus

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1204]
Proposal: [New vehicle data StabilityControlsStatus](https://github.com/smartdevicelink/sdl_evolution/edit/master/proposals/0253-New-vehicle-data-StabilityControlsStatus.md)

>This proposal is to add new vehicle data `StabilityControlsStatus` to know if stability controls like ESC, Traction Control etc. are active.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/841

**Comment by JulianKast** [comment]
Fixed with #1394
