### ISSUE TITLE
BeltStatus leftRearInflatableBelted 

### ISSUE THREAD

**Issue by jianglin2018** [smartdevicelink/sdl_java_suite#1210]
### Bug Report
The key value in Android should be changed from rearInflatableBelted to leftRearInflatableBelted to match what is in Core and the RPC Specs. 

BeltStatus.java
struct BeltStatus
public static final String KEY_REAR_INFLATABLE_BELTED = "rearInflatableBelted";

**Comment by mrapitis** [comment]
This fix should be included in the develop branch with the resolution of the issue linked below:
https://github.com/smartdevicelink/sdl_java_suite/issues/1078
