### ISSUE TITLE
InitializeProxy() failed after changing the language on the head unit

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1218]
### Bug Report

InitializeProxy failed after changing the language on the head unit

##### Reproduction Steps
1. Connect mobile, register mobile app and activate it on the head unit
2. Changing the language on the head unit

##### Expected Behavior
The proxy is restarted successfully

##### Observed Behavior
The proxy is restarted unsuccessfully

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.9.0
* Testing Against: SDL Core 5.1.3 + HMI running on our development environment.

##### Test Case, Sample Code, and / or Example App
Example App:https://github.com/smartdevicelink/sdl_java_suite/tree/master/android
Logs:[initializeProxyError.zip](https://github.com/smartdevicelink/sdl_java_suite/files/3844143/initializeProxyError.zip)

##### Occurrence:
100%

##### Recovery Method
Restart the mobile app, reconnect mobile

**Comment by joeygrover** [comment]
Hi @zhouxin627 , this has already been addressed in 4.10.0 with PR #1143.
