### ISSUE TITLE
Proxy does not call EndServiceCallback(11) after receiving OnHMIStatus(BACKGROUND).

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1219]
### Bug Report
Proxy does not call EndServiceCallback(11) after receiving OnHMIStatus(BACKGROUND).

##### Reproduction Steps
1. Register 2 apps:
・App1: navigation App for Android
・App2: navigation App for Android
2. Activate App1
3. App1 starts video streaming
4. Activate App2
5. App1 is not displayed in the HMI
    It runs continuously in the background.

##### Expected Behavior
1. Activate App1: SDL->App1.OnHMIStatus(FULL)
2. App1 starts Video streaming
3. Activate App2: SDL->App2.OnHMIStatus(FULL)
4. Deactivate App1: SDL->App1.OnHMIStatus(BACKGROUND)
5. Proxy sends EndService request:SDL<-App1.EndServiceCallback(11)
But there is no implementation for step 5

##### Observed Behavior
Proxy does not call App1.EndServiceCallback(11) after receiving OnHMIStatus(BACKGROUND).

##### OS & Version Information
* Android Version: 7.1
* SDL Android Version: 4.9.0
* Testing Against: SDL Core 5.1.3 + HMI running on our development environment.

##### Test Case, Sample Code, and / or Example App
App1:[NaviVideoApp1_0.030000.zip](https://github.com/smartdevicelink/sdl_java_suite/files/3844185/NaviVideoApp1_0.030000.zip)
App2:[NaviVideoApp2_0.030000.zip](https://github.com/smartdevicelink/sdl_java_suite/files/3844186/NaviVideoApp2_0.030000.zip)

##### Occurrence
100%

##### Recovery Method
None

**Comment by joeygrover** [comment]
Hi @zhouxin627, this has already been addressed in 4.10.0 with #1161.
