### ISSUE TITLE
There is a risk of data overflow that may give results leading to unintended behavior

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1227]
### Bug Report
There is a risk of data overflow that may give results leading to unintended behavior

##### Preconditions
1. App1.lastUpdateTime > App2.lastUpdateTime
2. The lastUpdateTime difference between APP1 and APP2 is outside of the values permitted for an int.

##### Reproduction Steps
1. Register App1
2. Activate App1

##### Expected Behavior
The RouterService of APP1 is used.

##### Observed Behavior
The RouterService of APP2 is used.

There is a risk of data overflow in the following statement.
`(int)(two.lastUpdateTime - one.lastUpdateTime);`

I know that maybe int is large enough to store the difference value.
This is certainly a theoretical risk but in practice there is almost no possibility of overflow happening.
And, I don't think it's necessary to compare the `lastUpdateTime`.
If the `routerServiceVersion` are different, we choose the newer one. If not, we can use either one.

```
int versionCompare =  two.routerServiceVersion	- one.routerServiceVersion;

if(versionCompare == 0){ //Versions are equal so lets use the one that has been updated most recently
	int updateTime =  (int)(two.lastUpdateTime - one.lastUpdateTime);
	if(updateTime == 0){
		//This is arbitrary, but we want to ensure all lists are sorted in the same order
		return	one.routerServiceComponentName.getPackageName().compareTo(two.routerServiceComponentName.getPackageName());
	}else{
		return updateTime;
	}
}else{
	return versionCompare;
}
```

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.9.0
* Testing Against: SDL Core 5.1.3 + HMI running on our development environment.

##### Occurrence
50%

##### Recovery Method
None

**Comment by bilal-alsharifi** [comment]
Thanks @zhouxin627 for reporting the issue. We made PR #1229  to fix the issue to avoid the potential overflow.
