### ISSUE TITLE
SDL failed to start video streaming if users enable WiFi on the head unit after the NaviAPP is activated

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1235]
### Bug Report
SDL failed to start video streaming if users enable WiFi on the head unit after the NaviAPP is activated

##### Reproduction Steps
1. Disable WiFi on the head unit
2. Connect the head unit to the phone via BT
3. Register a NaviAPP
4. Activate a NaviAPP
5. Enable WiFi on the head unit
6. Connect the head unit to the phone via BT+WiFi

##### Expected Behavior
The NaviAPP starts video streaming successfully

##### Observed Behavior
The NaviAPP starts video streaming unsuccessfully 

- Case ①: Activate the NaviAPP, then establish the WiFi connection within 150 seconds.
1. The WiFi connection is established.
2. Core sends the IP and Port information to Proxy.
`TransportEventUpdate(ip="192.168.1.100",port="32003")`
3. Proxy tries to establish a socket connection for 30 times, 
    but it does not use the updated IP and Port information.
4. Unable to establish the socket connection to the head unit.
5. The NaviAPP starts video streaming unsuccessfully

- Case ②: Activate the NaviAPP, after more than 150 seconds, then establish the WiFi connection.
1. The WiFi connection is established.
2. Core sends the IP and Port information to Proxy.
`TransportEventUpdate(ip="192.168.1.100",port="32003")`
3. Even though Proxy has received the updated IP and Port information,
    but it does not try to establish a socket connection to the head unit. 
4. The NaviAPP starts video streaming unsuccessfully

- In either case, the NaviAPP starts video streaming successfully on iOS.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.9.0
* Testing Against: SDL Core 5.1.3 + HMI running on our development environment

##### Occurrence
100%

##### Recovery Method
Kill the NaviAPP, connect BT+WIFI, restart the NaviAPP

**Comment by E-SAITO-TMC** [comment]
This is one of the issues that Toyota reported at the 11/18 Roadmap workshop.

**Comment by theresalech** [comment]
Toyota informed the Project Maintainer via email that they will be submitting a PR to resolve this issue by 2019-01-24.

**Comment by joeljfischer** [comment]
The PR and evolution proposal to fix this issue have been closed as inactive. This issue will also be closed as inactive. If desired, it can be re-opened, but the evolution proposal is the best place to start additional discussion on this issue.
