### ISSUE TITLE
SDL failed to start video streaming if users enable WiFi on the phone later 150s after the NaviAPP is activated

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1236]
### Bug Report
SDL failed to start video streaming if users enable WiFi on the phone later 150s after the NaviAPP is activated

##### Reproduction Steps
1. Disable WiFi on the phone
2. Enable WiFi on the head unit
3. Connect the head unit to the phone via BT
4. Register a NaviAPP
5. Activate a NaviAPP
6. After 150 seconds
7. Enable WiFi on the phone
8. Connect the head unit to the phone via BT+WiFi

##### Expected Behavior
When users enable WiFi on the phone, 
Proxy should try to establish a socket connection to the head unit.
The NaviAPP starts video streaming successfully

##### Observed Behavior
When users enable WiFi on the phone, 
Proxy does not try to establish a socket connection to the head unit. 
The NaviAPP starts video streaming unsuccessfully 

The NaviAPP starts video streaming successfully on iOS using the same steps.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.9.0
* Testing Against: SDL Core 5.1.3 + HMI running on our development environment

##### Occurrence
100%

##### Recovery Method
Kill the NaviAPP, connect BT+WIFI, restart the NaviAPP

**Comment by E-SAITO-TMC** [comment]
This is one of the issues that Toyota reported at the 11/18 Roadmap workshop.

**Comment by theresalech** [comment]
Toyota informed the Project Maintainer via email that they will be submitting a PR to resolve this issue by 2019-01-24.

**Comment by joeljfischer** [comment]
The PR and evolution proposal to fix this issue have been closed as inactive. This issue will also be closed as inactive. If desired, it can be re-opened, but the evolution proposal is the best place to start additional discussion on this issue.
