### ISSUE TITLE
The SDL Proxy does not send ChangeRegistration to the HU if users only change the hmiDisplayLanguage

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1241]
### Bug Report
The SDL Proxy does not send ChangeRegistration to the HU if users only change the hmiDisplayLanguage.

##### Preconditions
1. The app supports language changing
2. Default language settings:
The `hmiDisplayLanguage `is English
The vr/tts language is English

##### Reproduction Steps
Change the `hmiDisplayLanguage `to Japanese on the HU

##### Expected Behavior
The SDL Proxy sends `ChangeRegistration `to the HU

##### Observed Behavior
The SDL Proxy does not send `ChangeRegistration `to the HU

According to RPC Spec documents, it seems like when the HU's `hmiDisplayLanguage `or vr/tts language is different from the app's desired language, the app will send `ChangeRegistration `to change the registered language which is supported.
But at the SDL Proxy sourcecode's side, only the difference of vr/tts language will trigger `ChangeRegistration`.
The `hmiDisplayLanguage `and vr/tts language could be set separately in my use-case.

##### OS & Version Information
* Android Version:Android 8.0
* SDL Android Version:4.10.0
* Testing Against:SDL Core 5.1.3 + HMI running on our development environment.

##### Occurrence:
100%

##### Recovery Method:
None

**Comment by theresalech** [comment]
As noted on corresponding [iOS issue](https://github.com/smartdevicelink/sdl_ios/issues/1491#issuecomment-562723065), this must be fixed via an SDL Evolution Proposal.
