### ISSUE TITLE
Null pointer exception in startStream if hapticSpatialDataSupported is missing

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_java_suite#1245]
### Bug Report
SdlProxyBase throws a null pointer exception when calling startStream if hapticSpatialDataSupported is not included in VideoStreamingCapability.  The 
The hapticSpatialDataSupported parameter is optional in VideoStreamingCapability (please see link below).  The if statement (linked below) when checking getIsHapticSpatialDataSupported should first check to see if the value is null before checking the boolean value.

https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/MOBILE_API.xml#L3069

https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L8371

##### Reproduction Steps
Connect to a headunit that does not publish hapticSpatialDataSupported, however does publish other VideoStreamingCapability data. Attempt to start a video stream, take note of the null pointer.

##### Expected Behavior
startStream executes successfully with no null pointer exceptions.

##### Observed Behavior
startStream recieves a null pointer exception when connected to a head unit that does not publish hapticSpatialDataSupported.

##### OS & Version Information
* Android Version: Android 10
* SDL Android Version: Current develop as well as v4.10.1
* Testing Against: Bench setup with custom HMI

**Comment by joeygrover** [comment]
Please note the `SdlProxyBase` class is deprecated and should not be used. Therefore bugs found in a deprecated class will be of lower priority and developers should not expect fixes for those classes; this is inherent of the deprecation flag.

This is a small bug however, and can likely be patched in the next version.

**Comment by mrapitis** [comment]
The VideoStreamManager (non-deprecated) appears to have the same issue linked below.
https://github.com/smartdevicelink/sdl_java_suite/blob/develop/android/sdl_android/src/main/java/com/smartdevicelink/managers/video/VideoStreamManager.java#L116
