### ISSUE TITLE
Video streaming doesn't start again after closing the app using voice commands

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1248]
### Bug Report
When a video streaming app is closed using voice commands, the app will go to HMI Level `NONE`. If the user opens the app again and tries to start video streaming, the streaming will not work until the app is force closed.

##### Reproduction Steps
1. Start the video stream
2. Close the app using voice commands 
3. Open the app again and start the video stream

##### Expected Behavior
 Video should play again

##### Observed Behavior
Video streaming doesn't work

##### OS & Version Information
* Android Version: 9
* SDL Android Version: 4.10.1
* Testing Against: Sync 3.0 TDK

**Comment by theresalech** [comment]
Closed via #1250
