### ISSUE TITLE
SystemCapabilityManager doesn't fully support capability subscriptions 

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1255]
### Bug Report
 The capability subscription ability has been added to the `sdl_java_suite` library as described in this [proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md). The `SystemCapabilityManager` handles the `OnSystemCapabilityUpdated` notifications correctly. However, currently, there is no way to subscribe to a specific capability using the managers which makes capability subscription not very usable.
`sdl_ios` has that support so `sdl_java_suite` should add the ability to support capablity subscription to align with ios.

##### OS & Version Information
* Android Version: 4.10.1
* SDL Android Version: 10
* Testing Against: Core 6.0

**Comment by joeljfischer** [comment]
Closed via #1107
