### ISSUE TITLE
Proxy does not call App1.EndServiceCallback(11) after receiving App1.OnHMIStatus(BACKGROUND) when switching from App1 to App2 on HU.

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1278]
### Bug Report
Proxy does not call App1.EndServiceCallback(11) after receiving App1.OnHMIStatus(BACKGROUND)
when switching from App1 to App2 on HU.

##### Reproduction Steps
1. Register 2 apps:
・App1: navigation App for Android
・App2: navigation App for Android
2. Activate App1
3. App1 starts video streaming
4. Activate App2
5. App1 is not displayed in the HMI
    It runs continuously in the background.

##### Expected Behavior
1. Activate App1: SDL->App1.OnHMIStatus(FULL)
2. App1 starts Video streaming
3. Activate App2: SDL->App2.OnHMIStatus(FULL)
4. Deactivate App1: SDL->App1.OnHMIStatus(BACKGROUND)
5. Proxy sends EndService request:SDL<-App1.EndServiceCallback(11)
But there is no implementation for step 5

Our use case as follows:
・When switching from App1 to App2 on HU, App1's `VideoStreaming` is stopped and App2's `VideoStreaming` is started.
・When switching from App2 back to App1 on HU, App2's `VideoStreaming` is stopped and App1's `VideoStreaming` is resumed.

##### Observed Behavior
Proxy does not call App1.EndServiceCallback(11) after receiving App1.OnHMIStatus(BACKGROUND).

We asked this question in Slack and tried to use `dispose()` that could call App1.EndServiceCallback(11), but it could not help resolve the issue. 
App1's `VideoStreaming` isn't able to be resumed, because `dispose()` would stop App1's `VideStreamingManager`.

【Q&A in Slack】
https://smartdevicelink.slack.com/archives/C0K2W1V28/p1575962798112800

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.10.1
* Testing Against: SDL Core 6.0.1 + HMI running on our development environment.

##### Occurrence
100%

##### Recovery Method
None

**Comment by bilal-alsharifi** [comment]
Hi @zhouxin627, would it be possible to try and see if this issue exists in the current `develop` branch of the project? this [fix](https://github.com/smartdevicelink/sdl_java_suite/pull/1250) may affect the issue.

**Comment by zhouxin627** [comment]
Hi @bilal-alsharifi, I have tested the issue in the current `develop` branch, it has been fixed. Thank you.

**Comment by bilal-alsharifi** [comment]
Awesome. Thanks @zhouxin627  for confirming that.
