### ISSUE TITLE
USB transport drops remaining data after PSM FINISHED or ERROR state

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1279]
### Bug Report
Proxy can't decode some RPC Messages

### Reason
1. The USB driver of HU divides RPC Messages into many separate packages and then send them to Proxy.
2. In our case, when the data package at one time is less than 512B, it will be combined with the leading portion of the next RPC to be sent.
![image](https://user-images.githubusercontent.com/35795928/74904381-228a4e80-53ef-11ea-8bd1-0e6b756bc6eb.png)
※　Part①～Part⑤ are data packages after division by the USB driver

Part①～Part③：data packages of the first time
1. RPCMessage① can be decoded 
2. Since RPCMessage② has only the header portion but no trailing data, Proxy can't decode it and will discard it.

Part④～Part⑤：data packages of the second time
1. Since RPCMessage② has no header, Proxy can't decode it and will discard it.

### Solution
Data of the header portion should be not discarded and decoded with the second data package together.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: SDL Android Version: 4.10.1
* Testing Against: SDL Core 6.0.1 + HMI running on our development environment.

**Comment by joeygrover** [comment]
The library should be handling this correctly. There is specific logic to build out packets in this way. The `SdlPsm` is moved through states byte by byte. So the data received through the USB transport will be gone over 1 byte at a time. When the `SdlPsm` reaches the finished state it will build the packet and push it out. After this, it resets the `SdlPSM` and continues to parse through the received byte array. 

See [this loop in the `MultiplexUSBTransport`](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexUsbTransport.java#L246)

Can you confirm that the bytes being wrote out by Core/your USB driver are the same as they are being received in this loop?

**Comment by bilal-alsharifi** [comment]
Hi @zhouxin627, could you please confirm if this fix #1281 solves the issue?

**Comment by zhouxin627** [comment]
Hi @bilal-alsharifi, the issue has been fixed. Thank you.

**Comment by bilal-alsharifi** [comment]
Awesome. Thanks for confirming.

**Comment by JulianKast** [comment]
Fix has been merged
