### ISSUE TITLE
Responses to requests with reserved correlation IDs don't make it through the proxy

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_java_suite#128]
When an RPC request is sent with a reserved correlation ID, the head-unit rejects the request; however, due to the [logic in SdlProxyBase.java](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java#L1441-1603), the rejected message doesn't make it through the proxy to developer code.  This makes it look as if the request was ignored with no explanation.

**Comment by justinjdickow** [comment]
The proxy should check the correlation id and reject correlation ids that are set to the reserved values by the developer. Long term the app won't have to worry about correlation id

**Comment by bilal-alsharifi** [comment]
The new `LifecycleManager` that replaces `SdlProxyBase` calls the listener with a clear response message to let the developer know if the app is using a reserved correlation id:
https://github.com/smartdevicelink/sdl_java_suite/blob/715cb541c0034c7660fc152e418243c95ca96bce/base/src/main/java/com/smartdevicelink/managers/lifecycle/BaseLifecycleManager.java#L682
