### ISSUE TITLE
VideoStreaming does not start during HMI Level "LIMITED".

### ISSUE THREAD

**Issue by Yuki-Shoda-Nexty** [smartdevicelink/sdl_java_suite#1289]
### Bug Report
VideoStreaming does not start during HMI Level "LIMITED". 
In version 4.7.2, VideoStreaming can start only when the HMI Level is "FULL" by the check logic in Proxy.
However, an error is returned when the HMI Level is "LIMITED". As a result, video streaming cannot be started.

##### Reproduction Steps
1. Start a video application (HMI Level "FULL" is notified at this time)
2.Then,  start a media application (HMI Level "LIMITED" is notified to the video application at this time)
3.At the timing of step two, start video streaming.

##### Expected Behavior
VideoStreaming should start even if HMI Level = "LIMITED".

##### Observed Behavior
Error is returned, therefore, Video Streaming cannot be started.

##### OS & Version Information
* SDL Android Version: 4.7.2

**Comment by JulianKast** [comment]
Hi @Yuki-Shoda, I am having trouble replicating this error. Can you test this on SDL version 4.10.1?

**Comment by JulianKast** [comment]
@Yuki-Shoda  Can you verify if Branch bugfix/issue_1289 attached to pull request #1309 fixes the issue.

**Comment by theresalech** [comment]
@Yuki-Shoda-Nexty if you could please verify that branch `bugfix/issue_1289` (attached to pull request #1309) fixes this issue by 2020-04-09, we'd appreciate it!  We'll need to merge the PR at that time in order to begin testing for the Java Suite 4.11 Release.  Thanks!

**Comment by Yuki-Shoda-Nexty** [comment]
@JulianKast -san
@theresalech -san
My apologies for the delayed response.
We have confirmed that the issue was fixed with the attached bug fix.
