### ISSUE TITLE
Deprecate DeviceInfo.DEVICE_OS

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1290]
### Bug Report
The `DeviceInfo` RPC has `DEVICE_OS` variable and its value is hardcoded to be `Android`. This should be deprecated because it doesn't exist in the RPC spec. Also, the `DEVICE_OS` value will be incorrect if it is used in the `javaSE` library which uses the same RPC classes.

https://github.com/smartdevicelink/sdl_java_suite/blob/797b7a14a7fd67fdf6faa504865e4e22228858ef/base/src/main/java/com/smartdevicelink/proxy/rpc/DeviceInfo.java#L111

##### OS & Version Information
* SDL Android Version: 4.10.1

**Comment by JulianKast** [comment]
Fixed with PR "Deprecate DeviceInfo.DEVICE_OS #1291"
