### ISSUE TITLE
Issue in VoiceCommandManager.setVoiceCommands()

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1293]
### Bug Report
Currently in `BaseVoiceCommandManager`,  both `oldVoiceCommands` & `voiceCommands` are set to use the new value that is passed to the `setVoiceCommands()`:

https://github.com/smartdevicelink/sdl_java_suite/blob/797b7a14a7fd67fdf6faa504865e4e22228858ef/base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java#L130-L131

The `oldVoiceCommands` should use the current value of `voiceCommands`, not the new one.

##### OS & Version Information
* SDL Android Version: 4.10.1

**Comment by JulianKast** [comment]
Fixed with "Fix an issue in setVoiceCommands() #1295"
