### ISSUE TITLE
video/avc matching compontent failed

### ISSUE THREAD

**Issue by bill-lzb** [smartdevicelink/sdl_java_suite#1308]
[Delete any non-applicable sections, but we may ask for more information or close the issue if the template is not followed. Please reference the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) for further instructions on how to enter an issue.]

### Bug Report
[Summary]
VideoStreamManager start encoder failed.
※When I use SDL Android SDK 4.6.0, there is no problem.The error occurs when I use SDL Android SDK 4.9.0.
※This issue does not happen on XiaoMi Phone, but it does happen on HUAWEI phones(android 9 and 10).
##### Reproduction Steps
1. [Step 1]
Refer to [Android Guides 10/03/2019 11:49 AM], and write a Navigation app(With Mapbox).
2. [Step 2]
Connect the APP to a SDL Emulator with USB.
3. [Step 3]
Click the APP icon on the SDL Emlator

##### Expected Behavior
[Some expected behavior]
The video streaming should be successful
##### Observed Behavior
[Some observed behavior]
The following errors were output:
E/libc : Access denied finding property "ro.kirin.product.platform"
E/HwExtendedCodec: mime: video/avc matching compontent failed!
I/OMXClient: IOmx service obtained
I/Acodec: In onAllocateComponent create component, codec name: OMX.hisi.video.encoder.avc
W/HwExtendedUtils:hw configLocalPlayBack err = -22
W/OMXUtils: do not know color format 0x7f000001 = 2130706433
E/ACodec: [OMX.hisi.video.encoder.avc] failed to set output port definition parameters.
E/ACodec:[OMX.hisi.video.encoder.ac] configureCodec returning error -22
E/ACodec: signalError(omxError 0x80001001, internalWrror -22)
##### OS & Version Information
* Android Version: [API Level 26/28]
* SDL Android Version: [4.9.0]
* Testing Against: [A SDL Emulator developed by our company]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by JulianKast** [comment]
HI @bill-lzb, can you test with the latest release of SDL 4.10.1?

**Comment by joeljfischer** [comment]
I'm going to close this issue for inactivity. Please test with the 4.11.0 release and report if you still see the issue.
