### ISSUE TITLE
Lock Screen Icon is not cached

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_java_suite#1316]
### Bug Report
Currently we download the lock screen icon from the URL given to us by the `OnSystemRequest` every single time. We should cache the icon at the URL for 30 days and reuse that image for the given make / model.

##### Reproduction Steps
1. Connect to a head unit that provides a lock screen icon URL.
2. Note the download of the icon.
3. Reconnect to the head unit.

##### Expected Behavior
We should not need to re-download the image.

##### Observed Behavior
We re-download the image.

##### OS & Version Information
* Android Version: n/a
* SDL Android Version: n/a
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

**Comment by RHenigan** [comment]
iOS PR: 
https://github.com/smartdevicelink/sdl_ios/pull/1586
