### ISSUE TITLE
[SDL 0278] Screen Manager Template Management

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1327]
Proposal: [Screen Manager Template Management](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0278-screenmanager-layout-management.md)

> Adds a screen manager method for changing the current layout to a new layout.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/935

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0278 Revisions - Screen Manager Template Management](https://github.com/smartdevicelink/sdl_evolution/issues/1038).  Revisions include  adding new APIs that allow the update of color schemes, text, graphics, buttons, and template title at the same time the template is being updated.  Please reference the issue and proposal markdown file for revisions details.

**Comment by JulianKast** [comment]
Fixed with #1492
