### ISSUE TITLE
Align Video Streaming State with iOS

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_java_suite#1331]
Handling of the video streaming state within the JavaSuite needs to be aligned with the iOS platform. I believe this needs to be investigated further.

The original Enhancing onHMIStatus with a New Parameter for Video Streaming State proposal is linked below:
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0150-video-streaming-state.md

The iOS project merged pull request is linked below.  The pull request includes updates to the manager logic to handle streaming state processing.
https://github.com/smartdevicelink/sdl_ios/pull/994/files

The JavaSuite project merged pull request is linked below.  The pull request simply adds the parameter to the HMI status notification, it does not appear to include manager level changes. 
https://github.com/smartdevicelink/sdl_java_suite/pull/763/files

It also looks like the HMI status notification always returns STREAMABLE if the rpc spec version is less than 5.  In reality if the rpc spec version is less than 5, then the streamable state should be based on the hmi status level (e.g. full and limited states allow streaming)
https://github.com/smartdevicelink/sdl_java_suite/blob/master/base/src/main/java/com/smartdevicelink/proxy/rpc/OnHMIStatus.java#L142

**Comment by bilal-alsharifi** [comment]
Thanks @mrapitis for reporting the issue. I created PR #1334 to fix that. Can you please take a look at the branch and see if it fixes the issue?

**Comment by mrapitis** [comment]
@bilal-alsharifi thanks, we will plan to perform testing against the PR.  After a quick glance at the code, it looks like the streamable state in the OnHMIStatus RPC is still being set to STREAMABLE for all RPC spec versions below 5.... I believe the HMI level should be driving whether the state is STREAMABLE vs NONSTREAMABLE in versions below 5.

**Comment by bilal-alsharifi** [comment]
Thanks @mrapitis,  That is right Java Suite assumes that `VideoStreamingState`  is always `STREAMABLE` if it is null. I believe, iOS, is also doing a similar thing:
https://github.com/smartdevicelink/sdl_ios/blob/e94851172e2b99408eb4a033a557438406d3cde1/SmartDeviceLink/SDLStreamingVideoLifecycleManager.m#L615

So both libraries don't change the `VideoStreamingState` values based on `HMILevel`. However, they decide whether the HMI State is capable of streaming video based on both `HMILevel` and `VideoStreamingState`:

https://github.com/smartdevicelink/sdl_ios/blob/e94851172e2b99408eb4a033a557438406d3cde1/SmartDeviceLink/SDLStreamingVideoLifecycleManager.m#L819

**Comment by bilal-alsharifi** [comment]
We'd like to be able to include this fix in the 4.11 release scheduled for the end of this month. Testing of that release candidate will begin on Tuesday (4/14), so we'll need to merge this PR before then in order to include. Is it possible for you to have testing completed before Tuesday?
