### ISSUE TITLE
Disconnecting a cloud app doesn't free the port

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1339]
[Delete any non-applicable sections, but we may ask for more information or close the issue if the template is not followed. Please reference the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) for further instructions on how to enter an issue.]

### Bug Report
With a JavaSE application, when the app is terminated the websocketserver does not free the used port as expected, this results in the need to use a different port the next time the app is run.

##### Reproduction Steps
1. Run Hello_SDL_Java on a working port
2. Stop the application
3. Try to run Hello_SDL_Java on the same port

##### Expected Behavior
The app should be able to connect to the same port as before

##### Observed Behavior
The port is already in use and cannot be used the second time the app is run

**Comment by JulianKast** [comment]
Fixed in PR #1340
