### ISSUE TITLE
SystemRequest factory methods are not sufficient

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_java_suite#134]
[RPCRequestFactory](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/RPCRequestFactory.java#L62-84) has defined 2 methods for creating a SystemRequest request.

The first method assumes a request type of PROPRIETARY and assumes that the input data should be stored in the bulk data as a byte array.  Other methods using bulk data take in the byte array directly instead of converting the string to a byte array, so for consistency, these methods should be modified to meet project design.

The second method is for "legacy" hardware implementations, in which case the response is converted to a list of strings and an arbitrary boolean value is sent in the constructor.

**Comment by bilal-alsharifi** [comment]
Closing the issue as the `RPCRequestFactory` has been deprecated.
