### ISSUE TITLE
If an empty array is set for voice commands on the SDLMenuCell the AddCommand is rejected

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_java_suite#1341]
### Bug Report
If an empty array is set for `voiceCommands` when creating a `MenuCell` the resulting `AddCommand` is rejected by core because you can not send an empty array. 

The screen manager should not set the `vrCommands` parameter on the `AddCommand` if the `MenuCell`'s `voiceCommands` array is empty. 

##### Reproduction Steps
1. Create a `MenuCell` with an empty array set for the `voiceCommands` parameter and use the screen manager to send the menu.

##### Expected Behavior
The menu item should show up on the HMI

##### Observed Behavior
The menu item is rejected by Core because of the empty VR command list

##### OS & Version Information
* Android Version: n/a
* SDL Android Version: 4.11
* Testing Against: n/a

**Comment by joeljfischer** [comment]
See the iOS issue: https://github.com/smartdevicelink/sdl_ios/issues/1648

**Comment by JulianKast** [comment]
Fixed with #1354
