### ISSUE TITLE
Change lock screen logo and ensure correct contrast

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_java_suite#1342]
### Bug Report
The Java_Suite and iOS lock screen logos are currently different. The Java_Suite logo should change to align with the iOS logo (attached). Additionally, the iOS library does contrast checking against the background color of the lock screen to flip the logo color between white and black. The Java_Suite library should do the same thing.

![logo](https://trello-attachments.s3.amazonaws.com/56a78d5772a910f88b906e61/5ea86b3c4d5e327c1cc1c7c4/0e2436a3388098eb251073b71dcb8d5d/sdl_logo_black%402x.png)

##### Reproduction Steps
1. [Step 1]
2. [Step 2]
3. [Step 3]

##### Expected Behavior
[Some expected behavior]

##### Observed Behavior
[Some observed behavior]

##### OS & Version Information
* Android Version: [What version of Android are you using when the bug occurred]
* SDL Android Version: [What version of the library has this bug been seen on]
* Testing Against: [What you tested with to observe this behavior]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by RHenigan** [comment]
closed by PR #1355
