### ISSUE TITLE
Missing Foreground Permission causes fatal exception

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1343]
### Bug Report
If the router service attempts to start in the foreground without the manifest permission it will cause a fatal exception that will crash the app.

##### Reproduction Steps
1. Create a Test app without foreground permissions
2. Run application and connect to manticore

##### Expected Behavior
Observe Fatal exception

##### Observed Behavior
Application should not crash and should handle exception gracefully

**Comment by theresalech** [comment]
Reopening per #1359

**Comment by joeljfischer** [comment]
Checked by the integration validator with a runtime exception. Not worth doing a deep fix when we already check in DEBUG.
