### ISSUE TITLE
Style guide 

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1344]
### Bug Report
Different code styles are used in the library. A style guide should be created for the developers (including us) to follow to make the formatting more consistent in Java Suite.

##### Expected Behavior
Consistent code styling through the library.

##### Observed Behavior
Code styling is inconsistent through the library.

##### OS & Version Information
* SDL Android Version: 4.11.0

**Comment by theresalech** [comment]
Updated the wiki.
