### ISSUE TITLE
PermissionManager Should send callback when subscribing to listener

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1353]
### Bug Report
In the iOS library the PermissionManager the observer is called immediately with the permission status when subscribed. The android Library does not send a callback when PermissionManager.addListener() is called. This needs to be updated to ensure alignment with the iOS library.

##### Reproduction Steps
1. Add an OnPermissionChangeListener for the GetWayPoints RPC
2. Run the app and connect to Core or Manticore
3. Open Application on Core or Manticore

##### Expected Behavior
When the OnPermissionChangedListener is created, a callback should be sent with the current permissions status.

##### Observed Behavior
When the OnPermissionChangedListener is created a callback in not sent

##### Test Case, Sample Code, and / or Example App
iOS implementation: https://github.com/smartdevicelink/sdl_ios/blob/37cb5edcd23a8228b8db2f7dc5bd3360c88cb9f7/SmartDeviceLink/SDLPermissionManager.m#L147

**Comment by JulianKast** [comment]
Fixed in #1357
