### ISSUE TITLE
[proposal]Is there a way to let app know that the connected bluetooth device is a Sync device

### ISSUE THREAD

**Issue by yingchun1** [smartdevicelink/sdl_java_suite#1358]
Is there a way to let app know that the connected bluetooth device is a Sync device, We need to distinguish the connected bluetooth device is a Sync device or a normal bluetooth.

**Comment by joeygrover** [comment]
Closing as not an issue. Please use the [Slack Channel](https://slack.smartdevicelink.com/) to ask questions.

Sync is an OEM specific brand for their IVI. You can retrieve the OEM name and model from the `RegisterAppInterfaceResponse` through the [`vehicleType`](https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L4648) param
