### ISSUE TITLE
[SDL 0305] Homogenize TextFieldName

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1367]
Proposal: [Homogenize TextFieldName](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0305-homogenize-textfieldname.md)

> This proposal is to homogenize the enum `TextFieldName` in [`MOBILE_API.xml`](https://github.com/smartdevicelink/rpc_spec/blob/RPC-Generator/MOBILE_API.xml#L753) and [`HMI_API.xml`](https://github.com/smartdevicelink/sdl_core/blob/6.1.1/src/components/interfaces/HMI_API.xml#L539).

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1020

Steering Committee Decision:

>The Steering Committee voted to accept this proposal with the following revision: add requirement for documentation of enum values, as described in [this comment](https://github.com/smartdevicelink/sdl_evolution/issues/1020#issuecomment-637740732).

> The proposal .md file was updated to reflect these revisions on 6/3/2020.

**Comment by jordynmackool** [comment]
The proposal markdown file has been updated per the revisions included in the accepted with revisions review issue: [Revise SDL-0305 Homogenize TextFieldName](https://github.com/smartdevicelink/sdl_evolution/issues/1113). 

Accepted revisions can be reviewed in the merged PR here: https://github.com/smartdevicelink/sdl_evolution/pull/1109.

**Comment by jordynmackool** [comment]
closed via https://github.com/smartdevicelink/sdl_java_suite/pull/1585
