### ISSUE TITLE
[SDL 0306] Use Taskmaster To Handle Queuing Operations in Managers

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1368]
Proposal: [Use Taskmaster To Handle Queuing Operations in Managers](https://github.com/smartdevicelink/sdl_evolution/edit/master/proposals/0306-Use-Taskmaster-To-Handle-Queuing-Operations-In-Managers.md)

> This proposal is to include a new third party dependency called [`Taskmaster`](https://github.com/livio/Taskmaster) and start using it in the SDL Java Suite library. [`Taskmaster`](https://github.com/livio/Taskmaster) provides a queue oriented thread management solution to improve how managers handle queueing operations and make their logic easier to maintain and more efficient. This will allow the Java Suite library to better align with the iOS library that natively has this functionality through the OS.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1021

**Comment by RHenigan** [comment]
Closed with PR #1383
