### ISSUE TITLE
 Android app will not receive the notification of HU when the language is switched on the HU side.

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1372]
### Bug Report
Android app will not receive the notification of HU when the language is switched on the HU side.

##### Reproduction Steps
1. Connect the Android app to HU.
2. Switch the language on the HU side.(For example:change the language of HU side from English to Japanese)

##### Expected Behavior
After language switching, app will unregister first and then register again.

##### Observed Behavior
After language switching, app will unregister first but not register again.

##### Reason
The guideline to the AddNotificationLisener of the proxy 4.10.1 is modified.
https://www.smartdevicelink.com/zh-hans/guides/android/getting-started/integration-basics/#listening-for-rpc-notifications-and-events						
Listening for RPC notifications and events						

The guideline adjustment is not a problem, but there is a defect in the corresponding program.

##### Sequence Diagram
![sequence (1)](https://user-images.githubusercontent.com/35795928/83983887-e1ea1d00-a96c-11ea-9ab8-b8cdb3edad7a.png)
If the app connects with HU, the sdlmanager saves the onRPCNotificationListeners.
Since the app succeeds register, the sdlmanager sets the onPRCNotificationListeners to NULL.
After the language switching, the app is registered again, because the onRPCNotificationListeners is NULL, so the app will not receive the notification of HU.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.11.0
* Testing Against: SDL Core 6.1.0 + HMI running on our development environment.

##### Occurrence:
100%

##### Recovery Method:
Reconnect the app

**Comment by JulianKast** [comment]
Hi! @zhouxin627, Can you clarify the reproductions steps and expected behavior, what do you mean by "Switch the language on the mobile side"?

**Comment by zhouxin627** [comment]
Hi @JulianKast, I apologize that there is something wrong with the previous content.I have updated the reproductions steps and expected behavior.

**Comment by theresalech** [comment]
Closing this issue, as the PM believes it to be resolved with PR #1390.  If the reporter is still seeing the issue, please advise, and we can reopen.  Thanks!
