### ISSUE TITLE
Android app will become an ANR(Freeze) when repeatedly connect and disconnect the BT/USB connection.

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1373]
### Bug Report
Android app will become an ANR(Freeze) when repeatedly connect and disconnect the BT/USB connection.

##### Reproduction Steps
1. Repeatedly connect and disconnect the BT/USB connection about 10 times.

##### Expected Behavior
Android app will not become an ANR(Freeze).

##### Observed Behavior
Android app becomes an ANR(Freeze).

##### Reason
The guideline to the AddNotificationLisener of the proxy 4.10.1 is modified.
https://www.smartdevicelink.com/zh-hans/guides/android/getting-started/integration-basics/#listening-for-rpc-notifications-and-events
Listening for RPC notifications and events
The guideline adjustment is not a problem but it exposed potential problems.

##### Sequence Diagram
![sequence (2)](https://user-images.githubusercontent.com/35795928/83984429-232ffc00-a970-11ea-8c60-c61476ef4653.png)

If it operates in the order of ①->③->②->④ / ①->③->④->②, there is a DeadLock and becomes an ANR.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.11.0
* Testing Against: SDL Core 6.1.0 + HMI running on our development environment.

##### Occurrence:
10%

##### Recovery Method:
Restart the app

##### Logs:
[log.txt](https://github.com/smartdevicelink/sdl_java_suite/files/4743392/log.txt)

**Comment by theresalech** [comment]
@zhouxin627 we believe this issue has been resolved in https://github.com/smartdevicelink/sdl_java_suite/pull/1366.  Can you please re-test using the `develop` branch?

**Comment by theresalech** [comment]
Closing this issue, as the PM believes it to be resolved with PR #1366.  If the reporter is still seeing the issue, please advise, and we can reopen. Thanks!
