### ISSUE TITLE
Add ForegroundServiceType Parameter to HelloSdl Project

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1374]
### Bug Report
The ForegroundServiceType parameter is a new parameter added in Android SDK 29. For a smartdevice link app we should use the connectedDevice flag. This is not enforced yet by Android but should be added now.
https://developer.android.com/reference/android/R.attr#foregroundServiceType

##### OS & Version Information
* Android Version: 29+

**Comment by JulianKast** [comment]
Fixed in #1376
