### ISSUE TITLE
ANRs (Application Not Responding) occur when switching from App1 to App2 on HU.

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1398]
### Bug Report
ANRs (Application Not Responding) occur when switching from App1 to App2 on HU.

##### Reproduction Steps
1. Register 2 apps:
・App1: navigation App for Android
・App2: navigation App for Android
2. Activate App1
3. App1 starts video streaming
4. Activate App2
5. App1 is not displayed in the HMI
    It runs continuously in the background.

##### Expected Behavior
ANRs (Application Not Responding) doesn't occur

##### Observed Behavior
ANRs (Application Not Responding) occur

##### Reason
When NaviApp's HMIStatus is changing from` (HMI_FULL,STREAMABLE) `to `(HMI_BackGround,NOT_STREAMABLE)`:
1. Naviapp receives `OnHMIStatus(HMI_BACKGROUND,NOT_STREAMABLE)` and stops getting data from `BlockingQueue`.
2. Naviapp sends `EndNaviService` to HU.
3. Naviapp receives `EndNaviServiceACK`, stops `Encode`, and stops the output of data to the `BlockingQueue`.

The maximum size of `BlockingQueue` is 2, and if the data is over, it will block and the app will be ANR.
At the time when the data acquisition of the above item1 is stopped, the data filling of the above item3 is not stopped.
Between item1 to item3, if a large amount of data is output to the `BlockingQueue`, the app becomes ANR.

Sequence Diagram
![image](https://user-images.githubusercontent.com/35795928/85660234-599ba400-b6f0-11ea-91c7-3fe346e0a045.png)

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.11.0
* Testing Against: SDL Core 6.1.0 + HMI running on our development environment

##### Occurrence:
5%

##### Recovery Method:
kill the app and restart

##### Logs:
[1398_log.txt](https://github.com/smartdevicelink/sdl_java_suite/files/4857607/1398_log.txt)

**Comment by joeygrover** [comment]
Do you have the log for the ANR?

**Comment by zhouxin627** [comment]
Hi @joeygrover, I have added the log file called `1398_log.txt`

**Comment by zhouxin627** [comment]
Hi @joeygrover，do you have a plan to resolve this issue.

**Comment by joeygrover** [comment]
@zhouxin627 I have opened a PR (#1480) that potentially solves the issue. Can you please test and report your results?

**Comment by JulianKast** [comment]
Fixed with #1480

**Comment by Shohei-Kawano** [comment]
@joeygrover -san
I reply on @zhouxin627 behalf.
We have confirmed your PR. It's OK for us. Thanks.
