### ISSUE TITLE
ClassCastException when calling RPC getter method returning Float type

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_java_suite#1407]
### Bug Report
A class cast exception occurs when an RPC getter method such as ```getPressure()``` inside of ```SingleTireStatus``` is called. This is because of the method used for JSON marshalling inside of the Java suite (code linked below). The JSON hashtable serializer method will store a whole number as an Integer and a whole number with a decimal included as a Double. When an RPC class method such as ```getPressure()``` inside of ```SingleTireStatus``` attempts to retrieve data from its corresponding list a class cast exception will occur because the method has a Float signature, but the data type is a Double.
https://github.com/smartdevicelink/sdl_java_suite/blob/master/base/src/main/java/com/smartdevicelink/marshal/JsonRPCMarshaller.java

Pressure is defined as a Float in the RPC spec
https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L1341

The Java suite throws a ClassCastException when calling the getPressure() method
https://github.com/smartdevicelink/sdl_java_suite/blob/master/base/src/main/java/com/smartdevicelink/proxy/rpc/SingleTireStatus.java#L142

One possible solution to the this issue is to update getter methods to first call the ```SdlDataTypeConverter``` to ensure the proper type is returned for any method that returns a Float value. A similar approach is already being used for retrieving the speed parameter in getVehicleData (please see links below).  Its possible updating the central getFloat() methods to first call the SdlDataTypeConverter would be the best solution.

Speed is defined as a float in the RPC spec
https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml#L2068

The Java suite first calls the ```SdlDataTypeConverter``` before returning the value for speed in getVehicleData response to ensure type safety
https://github.com/smartdevicelink/sdl_java_suite/blob/93778656113f0023ec7025281b77e28000a1f5bd/base/src/main/java/com/smartdevicelink/proxy/rpc/GetVehicleDataResponse.java#L120

##### Reproduction Steps
1. Register a test app with SDL core and activate it on the HMI
2. Ensure the HMI is configured to send data for an RPC method that returns a Float data type
3. Take note of the class cast exception

##### Expected Behavior
No class cast exception occurs.

##### Observed Behavior
Class cast exception occurs.

##### OS & Version Information
* Android Version: Android 10
* SDL Android Version: 4.11.1
* Testing Against: Sync Head Unit

**Comment by theresalech** [comment]
Hi @mrapitis - we've implemented PR #1428 to resolve this issue.  Can you please test and confirm that the PR resolves the issue for you as well?  Thank you!
