### ISSUE TITLE
TransportManager.exitLegacyMode () : NullPointerException 

### ISSUE THREAD

**Issue by pwerner00** [smartdevicelink/sdl_java_suite#1412]
### Bug Report
[
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.smartdevicelink.transport.TransportManagerBase.close(long)' on a null object reference
at com.smartdevicelink.protocol.SdlProtocolBase$2.onTransportDisconnected (Unknown Source: 27)
at com.smartdevicelink.transport.TransportManager.exitLegacyMode (Unknown Source: 53)
at com.smartdevicelink.transport.TransportManager$2.onReceive (Unknown Source: 18)
]

Same issue as closed issue #1213 
##### Reproduction Steps
Issue found by FordPass using Dynatrace.
Looks like this is occuring duing clean up and thread is crashing while cleaning up

##### Expected Behavior
Clean up cleaning without crash

##### Observed Behavior
No observable behavior by customer - only noticed through Dynatrace logs

##### OS & Version Information
* Android Version: Several versions
* SDL Android Version: 4.9.1
* Testing Against: Dynatrace logs from production FordPass app

**Comment by joeygrover** [comment]
`SDL Android Version: 5.90` I believe this is a typo, the current library version is 4.11.1

**Comment by pwerner00** [comment]
Yes sorry - 4.9.1

**Comment by bilal-alsharifi** [comment]
Thanks for reporting the issue. A potential race condition could happen when multiple threads access that same code block. For example, one thread could check if the`TransportManager` is not `null` and if another thread changed the object to `null` immediately after that check, an NPE could happen as described in the issue.

**Comment by theresalech** [comment]
Hi @pwerner00, we are closing this issue as resolved by PR #1454. Please let us know if you continue experiencing the issue after incorporating these changes (to be released with Java Suite 5.0 in November).
