### ISSUE TITLE
RPC Generator is generating enum values with wrong capitalization

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1425]
### Bug Report
The RPC Generator is generating enum values with the wrong capitalization. For example, for the `subtleAlertIcon` in the `ImageFieldName`

```
<enum name="ImageFieldName" since="1.0">
    <!-- New Values -->
    <element name="subtleAlertIcon">
        <description>The image of the subtle alert; applies to `SubtleAlert` `alertImage`</description>
    </element>
</enum>
```

##### Expected Behavior
The generator should generate the following:
```
public enum ImageFieldName {	
	.
	.
	.
	subtleAlertIcon,
}
```

##### Observed Behavior
The generator actually generates that:
```
public enum ImageFieldName {	
	.
	.
	.
	SUBTLE_ALERT_ICON,
}
```

##### OS & Version Information
* Android Version: N/A
* SDL Android Version: 4.12.0
* Testing Against: N/A

**Comment by JulianKast** [comment]
Fixed with #1437
