### ISSUE TITLE
SystemCapabilityManager & HapticInterfaceManager should be moved to the managers package

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1432]
### Bug Report
Some managers (like `SystemCapabilityManager` & `HapticInterfaceManager`) that were created before officially adding the managers' layer in sdl_java_suite are located in the `proxy` package. They couldn't be moved to the managers package in the past because it is a breaking change. But now, with the new major release, it is a good time to move them to the right package.

**Comment by theresalech** [comment]
Closed via #1431
