### ISSUE TITLE
RPC Generator is not generating the corresponding Javadoc for min & max attributes 

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1438]
### Bug Report
RPC Generator is not generating the corresponding Javadoc for min & max attributes. It is ignoring `minsize` & `maxsize` attributes for arrays. `minvalue`, `maxvalue`,  and `defvalue` for numbers. And also `minlength`, `maxlength` for strings.

**Comment by theresalech** [comment]
Closed via #1439
