### ISSUE TITLE
RPC Generator needs to be updated to generate correct Android X imports

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1444]
### Bug Report
The RPC generator generates imports for the old Android support libraries. Now that the project is using the Android X libraries, the generator needs to be updated to generate the correct imports. 

##### Reproduction Steps
1- Generate RPC for one of the responses for example `AlertResponse`
2- Look at the annotation import

##### Expected Behavior
```
import androidx.annotation.NonNull;
```

##### Observed Behavior
```
import android.support.annotation.NonNull;
```

**Comment by JulianKast** [comment]
Fixed with #1445
