### ISSUE TITLE
Deprecated RPC APIs that don't exist in the spec should be removed 

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1446]
### Bug Report
The Java Suite library includes some RPCs and RPC APIs that do not exist in the spec. They were deprecated in the past but couldn't be removed because it is a major change. But now with the new major release, they should be removed. Some examples are:

https://github.com/smartdevicelink/sdl_java_suite/blob/7f12aef2f619380fc625cb72bfa1a1948d425181/base/src/main/java/com/smartdevicelink/proxy/rpc/PutFile.java#L399

https://github.com/smartdevicelink/sdl_java_suite/blob/7f12aef2f619380fc625cb72bfa1a1948d425181/base/src/main/java/com/smartdevicelink/proxy/rpc/OnButtonPress.java#L185

https://github.com/smartdevicelink/sdl_java_suite/blob/7f12aef2f619380fc625cb72bfa1a1948d425181/base/src/main/java/com/smartdevicelink/proxy/rpc/OnSdlChoiceChosen.java#L42

**Comment by JulianKast** [comment]
Fixed with #1447
