### ISSUE TITLE
RPC Generator should use @deprecated annotation in JavaDocs when applicable

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1448]
### Bug Report
Currently the generator for the RPC Spec will add the below annotation to the javadocs when the `since` attribute is available.
`@since SmartDeviceLink X.X.X`

When something is deprecated in the RPC spec this is still the case. This can be confusing because it could be interpereted and something being added and deprected within the same version. We would like to change this behavior in the generator.
If the `deprecated` attribute is true and the `since` attribute is available the JavaDocs should instead include:
`@deprecated in SmartDeviceLink X.X.X`

RPC Spec Mobile API Versioning Proposal: https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0089-mobile-api-versioning.md

**Comment by theresalech** [comment]
Closed via #1453
