### ISSUE TITLE
Lists with initial values of null are not returned properly in RPCs

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_java_suite#1473]
### Bug Report
The method `formatObject` in the RPCStruct is responsible for correctly returning objects stored in the RPC hash tables. One of the types includes lists. The issue with a List type object is that we must figure out if the list is a list of pre-formatted hash tables that need to be formatted into the object type we are looking for or if they are already formatted and started as the supplied class.

This method works for most cases except when `null` is the first object in a list. Since null is not considered a type of the class supplied or HashTable, the method will return null.

##### Reproduction Steps

Using unit tests we are able to see this behavior:

```java
		WindowCapability capability = new WindowCapability();

		List<TextField> listNull = new ArrayList<>();
		listNull.add(new TextField(TextFieldName.mainField4, CharacterSet.UTF_8, 500, 8));
		listNull.add(null);
		assertNotNull(listNull);
		capability.setTextFields(listNull);
		assertNotNull(capability);
		assertNotNull(capability.getTextFields()); //Passes

		List<TextField> nullList = new ArrayList<>();
		nullList.add(null);
		nullList.add(new TextField(TextFieldName.mainField4, CharacterSet.UTF_8, 500, 8));
		assertNotNull(nullList);
		capability.setTextFields(nullList);
		assertNotNull(capability);
		assertNotNull(capability.getTextFields()); //Fails

```

##### Expected Behavior
- The method should return a valid list that includes the `null` value cast as whatever the list should be filled with.

##### Observed Behavior
- The method will return a null object instead of a list which then gets cast to a `null` list.

**Comment by theresalech** [comment]
Closed via #1474
