### ISSUE TITLE
Resolve Typos in `SdlProxyBase`

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_java_suite#1511]
### Bug Report
The following typos need to be resolved within the following file path `sdl_java_suite/android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java`. 

##### Observed Behavior/ Expected Behavior
- The word `Intial` should be `Initial` in the description for `@param initPrompt`
- The word `beginging` should be `beginning` in the description for `@param iOffset`
- The word `notificaiton` should be `notification` in the following sentence "This method is no longer valid and will not remove the listener for the supplied notificaiton id"  
- The duplication of the word `are` the description of `@param position` should be removed

**Comment by joeygrover** [comment]
This class has been removed, closing as no longer an issue.
