### ISSUE TITLE
Some cloud apps fail to download icons 

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1513]
### Bug Report
Some cloud apps fail to download icons because the HTTP request gets rejected by the server. When that happens, the cloud app gets an error message like this:

``` 
Unable to download file - https://searchengineland.com/figz/wp-content/seloads/2015/12/google-amp-fast-speed-travel-ss-1920-800x450.jpg - Server returned HTTP response code: 403 for URL: https://searchengineland.com/figz/wp-content/seloads/2015/12/google-amp-fast-speed-travel-ss-1920-800x450.jpg
```

It seems that this happens because the user agent is not set in the HTTP request and some servers reject the request when the agent is not set. 

##### Reproduction Steps
1. Create a cloud app and use this as an icon:
```
https://searchengineland.com/figz/wp-content/seloads/2015/12/google-amp-fast-speed-travel-ss-1920-800x450.jpg
```
2. Start the cloud app
3. Observe the app icon on HMI

##### Expected Behavior
The app icon gets downloaded and displayed correctly on HMI

##### Observed Behavior
The app icon download fails 

##### OS & Version Information
* Android Version: N/A
* SDL Android Version: 4.12.0
* Testing Against Core 7.0/ Generic HMI

**Comment by theresalech** [comment]
Closed via #1514
