### ISSUE TITLE
LockScreen behavior is incorrect for Display Always and Dismissible

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1515]
### Bug Report
When `LockScreenConfig` `DisplayMode` is set to `DISPLAY_MODE_ALWAYS` and `enableDismissGesture` is set to true there is an issue with how the lock screens are being displayed and dismissed.

Part 1
##### Reproduction Steps
1. Create a new `LockScreenConfig` and set `DisplayMode` to `DISPLAY_MODE_ALWAYS` and set `enableDismissGesture` to true
2. Make sure DD is off on Core or Manticore and then connect the app to Core or Manticore

##### Expected Behavior
A Dismissible lockScreen should appear

##### Observed Behavior
A lockScreen that is not dismissible is presented

Part 2
##### Reproduction Steps
1.  Continue from part 1 and set DD to ON in Core or Manticore
2. The LockScreen should change and now be dismissible
3. Dismiss the lockscreen

##### Expected Behavior
The LockScreen should be dismissed and the user should be able to interact with the application

##### Observed Behavior
The LockScreen is dismissed but there is another LockScreen presented that the user cannot dismiss

##### Test Case, Sample Code, and / or Example App
Set in SdlService:
`LockScreenConfig lockScreenConfig = new LockScreenConfig();` `lockScreenConfig.setDisplayMode(LockScreenConfig.DISPLAY_MODE_ALWAYS);`
 `lockScreenConfig.enableDismissGesture(true);`
 `builder.setLockScreenConfig(lockScreenConfig);`

**Comment by theresalech** [comment]
Closed via #1517
