### ISSUE TITLE
ScreenManager doesn't work when app register on backup transport

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1518]
### Bug Report
`ScreenManager` doesn't work when the app has primary and backup transport connected, then the primary transport disconnect and the app registers on the backup transport.

##### Reproduction Steps
1. Install hello sdl android and make sure it uses multiplex as a transport 
2. Connect the app to TDK via Bluetooth
3. Do not put the app in HMI `FULL`
4. Connect a USB cable and wait for USB to fully connect
5. Disconnect Bluetooth from the phone
6. Put the app in HMI `FULL`

##### Expected Behavior
Text and graphics should be displayed on the screen

##### Observed Behavior
Notice that nothing is displayed on the screen

##### OS & Version Information
* Android Version: 11
* SDL Android Version: 4.12.0
* Testing Against: Ford SYNC 3.4

**Comment by JulianKast** [comment]
Fixed with #1519
