### ISSUE TITLE
There are a few deprecated functions that don't link to the correct function.

### ISSUE THREAD

**Issue by santhanamk** [smartdevicelink/sdl_java_suite#1536]
### Bug Report
There are a few deprecated functions that don't link to the correct function.

##### Reproduction Steps
1. Download the RC2_5.0 code from https://github.com/smartdevicelink/sdl_java_suite/releases/tag/RC2_5.0.0.
2. Observe the code in `OnSystemRequest.java`
3. Observe the code in `TouchEvent.java`

##### Expected Behavior
Deprecated functions should link to the correct function.

##### Observed Behavior
There are a few deprecated functions don't link to the correct function.

##### OS & Version Information
* Android Version: [What version of Android are you using when the bug occurred]
* SDL Android Version: RC2_5.0 (pre-existing)
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App
`OnSystemRequest.java`

line 314 `setOffset(Integer offset)`  >-- this would need "`use {@link #setOffset(Long)} instead`" in the `@deprecated` tag
line 380 `setLength(Integer length)` >-- this would need "`use {@link #setLength(Long)} instead`" in the `@deprecated` tag

`TouchEvent.java`

line 137 `getTs()` -> this would need "`use {@link #getTimestamps()}()} instead`" in the `@deprecated` tag
line 176 `setTs(List<Long> ts)` -> this would need "use {@link #setTimestamps(List)} instead" in the `@deprecated` tag
line 188 `getC()` ->  this would need "`use {@link #getTouchCoordinates()} instead`" in the `@deprecated` tag
line 204 `setC(List<TouchCoord> c)` -> this would need "`use {@link #setTouchCoordinates(List)} instead`" in the `@deprecated` tag

@theresalech I messaged about this on the Slack channel.  It is not an issue in the RC2_5.0 code, and doesn't need to be fixed right away.  Per @joeygrover it is a minor issue.

**Comment by JulianKast** [comment]
Fixed with #1537
