### ISSUE TITLE
SdlManager builder warning in 4.12+ when using Kotlin

### ISSUE THREAD

**Issue by bmcisaa1-ford** [smartdevicelink/sdl_java_suite#1567]
### Bug Report

There is a Android Studio warning introduced in SDL 4.12 +  when using the manager builder

##### Reproduction Steps

Type BaseSdlManager.Builder! is inaccessible in this context due to: public open class Builder defined in com.smartdevicelink.managers.BaseSdlManager

```kotlin
val builder : SdlManager.Builder = SdlManager.Builder(this, APP_ID, "Sdl_App", listener)
builder.setAppTypes(appType)
builder.setTransportType(transport)
builder.setAppIcon(appIcon)
sdlManager = builder.build()
sdlManager?.start()
```
##### Expected Behavior
No Warning, Kotlin compatibility. 

##### Observed Behavior
A warning

##### OS & Version Information
* Android Version: 11
* SDL Android Version: 4.12 +
* Testing Against: Kotlin version of hello sdl

##### Test Case, Sample Code, and / or Example App
see code snippet above

**Comment by bmcisaa1-ford** [comment]
@dsquir11 Just adding you for tracking.

**Comment by joeygrover** [comment]
While the warnings are present the functionality should continue to work in Kotlin. I don't have timing as to when this will be addressed in a release yet but as a workaround I would suggest just creating a Java class `SdlManagerFactory` that can be accessed from your Kotlin code with a static method to create an `SdlManager` instance and handle all the builder code there. This will prevent the warning from the Kotlin side.

```java
package com.sdl.test;

import android.content.Context;

import com.smartdevicelink.managers.SdlManager;
import com.smartdevicelink.managers.SdlManagerListener;
import com.smartdevicelink.managers.file.filetypes.SdlArtwork;
import com.smartdevicelink.proxy.rpc.enums.AppHMIType;
import com.smartdevicelink.transport.MultiplexTransportConfig;

import java.util.Vector;

public class SdlManagerFactory {

    public static SdlManager createSdlManager(Context context, String appID,
                                                String appName, SdlManagerListener listener,
                                                Vector<AppHMIType> appTypes, SdlArtwork appIcon){

        SdlManager.Builder builder = new SdlManager.Builder(context, appID, appName, listener);
        builder.setAppTypes(appTypes);
        builder.setTransportType(new MultiplexTransportConfig(context, appID));
        builder.setAppIcon(appIcon);
        return builder.build();
    }
}
```

Then from the Kotlin side:

```kotlin
 val sdlManager = SdlManagerFactory.createSdlManager(this, APP_ID, APP_NAME, listener, appTypes, appIcon );

```

**Comment by bmcisaa1-ford** [comment]
Thanks for the workaround. I've forwarded it on to the appropriate team. Hope all is well!

**Comment by JulianKast** [comment]
SmartDeviceLink Android guides were updated with a Kotlin support page under FAQ. https://smartdevicelink.com/en/guides/android/frequently-asked-questions/kotlin-support/
