### ISSUE TITLE
[SDL 0323] - Align video streaming parameters with VideoStreamingCapability

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_java_suite#1569]
Proposal: [Align video streaming parameters with VideoStreamingCapability](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md)

> When Android SDL application starts video streaming, a developer can specify VideoStreamingParameters, but before actually starting the streaming, those parameters need to be aligned with VideoStreamingCapability returned by head units. The same is true for iOS SDL application; i.e. a developer can specify customVideoEncoderSettings, but those settings need to be aligned with VideoStreamingCapability.

Steering Committee Decision: 
The Steering Committee voted to accept the proposal on 2020-11-24. Xevo, the authoring company of the proposal shared that this proposal's [motivation](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0323-align-VideoStreamingParameter-with-capability.md#motivation) was found while working on the implementation for [SDL 0274](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0274-add-preferred-FPS.md) (an already accepted proposal).
 

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1094

**Comment by shiniwat** [comment]
Because this feature is implemented in the same way with preferred FPS (SDL 0274), and implementation has some dependency on SDL 0292, I have added [the commit](https://github.com/smartdevicelink/sdl_java_suite/pull/1389/commits/3adc0eaf12c453ad4ca4bf2adcff92408bf4350d) into another PR. Please see issue #1389 for details. Thanks.
