### ISSUE TITLE
Only auto-overwrite non-persistent files on RPC v4.3 and below

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_java_suite#1580]
### Bug Report
We currently auto-overwrite non-persistent files on all connections due to a bug that was fixed in Core v4.3.1 (https://github.com/smartdevicelink/sdl_core/issues/1393). We should change that to only apply that workaround on RPC v4.3 and below.

##### Reproduction Steps
1. Connect to a head unit running >= Core v4.3.1
2. Attempt to upload an ephemeral artwork
3. Attempt to upload the same ephemeral artwork

##### Expected Behavior
The artwork should not be re-uploaded

##### Observed Behavior
The artwork is re-uploaded

##### OS & Version Information
* Android Version: n/a
* SDL Android Version: 5.0.0
* Testing Against: Manticore (Core 7.0.0 / Generic HMI 0.9.0)

##### Test Case, Sample Code, and / or Example App
n/a

**Comment by JulianKast** [comment]
Fixed with #1582
