### ISSUE TITLE
[SDL 0293] Enable OEM exclusive apps support

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_java_suite#1588]
**Proposal:** [Enable OEM exclusive apps support](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0293-vehicle-type-filter.md)

> This feature will enable SDL adopters to provide exclusive apps to their users depending on vehicle type. The proposal describes a way to share vehicle type information before sending the Register App Interface request.

**Review:** https://github.com/smartdevicelink/sdl_evolution/issues/971

**Steering Committee Decision:** 
The Steering Committee voted to accept this proposal with the following revisions:

The author is to update the proposal to include the requested requirement for the Java Suite Library to have two pull requests submitted for this feature. The reasoning as to why is documented in [this comment ](https://github.com/smartdevicelink/sdl_evolution/issues/971#issuecomment-730557977)and should be included in the proposal.

The proposal .md file was updated to reflect these revisions on 12/14/2020.

**Comment by jordynmackool** [comment]
The proposal markdown file has been updated per the revisions included in the accepted with revisions review issue: [SDL 0293 Revisions - Enable OEM exclusive apps support](https://github.com/smartdevicelink/sdl_evolution/issues/1108). 

Accepted revisions can be reviewed in the merged PR here: https://github.com/smartdevicelink/sdl_evolution/pull/1106.

**Comment by JulianKast** [comment]
Implemented in #1604
