### ISSUE TITLE
KeyboardProperties.autoCompleteText does not get set in PresentChoiceSetOperation

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1593]
### Bug Report
It seems that in `PresentChoiceSetOperation`, only the new `KeyboardProperties.autoCompleteList` is updated and not the deprecated `KeyboardProperties.autoCompleteText` 
https://github.com/smartdevicelink/sdl_java_suite/blob/e1ef1b496bcc874e92a850fa7b0c9cb70d5bf6a3/base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PresentChoiceSetOperation.java#L346

Which means that, on head units that doesnt support `autoCompleteList` (RPC < 6.0), the auto complete text will not be updated if the app calls `keyboardAutocompleteCompletionListener.onUpdatedAutoCompleteList(...)`

##### Reproduction Steps
1. Use a head unit that supports has an older RPC version (RPC < 6.0)
2. Call `ScreenManager().presentSearchableChoiceSet()` and use this keyboard listener that updates the `AutoCompleteList` on the head unit when the user types types something:
```
KeyboardListener keyboardListener = new KeyboardListener() {
            @Override
            public void onUserDidSubmitInput(String inputText, KeyboardEvent event) {
            }

            @Override
            public void onKeyboardDidAbortWithReason(KeyboardEvent event) {
            }

            @Override
            public void updateAutocompleteWithInput(String currentInputText, KeyboardAutocompleteCompletionListener keyboardAutocompleteCompletionListener) {
                keyboardAutocompleteCompletionListener.onUpdatedAutoCompleteList(Arrays.asList("one", "two", "three"));
            }

            @Override
            public void updateCharacterSetWithInput(String currentInputText, KeyboardCharacterSetCompletionListener keyboardCharacterSetCompletionListener) {
            }

            @Override
            public void onKeyboardDidSendEvent(KeyboardEvent event, String currentInputText) {
            }
        };
```
        
3. When the choices get displayed on the head unit, use the head unit keyboard to type anything to search in the choices 

##### Expected Behavior
The autocomplete list should get updated and it should include "one" as an auto-complete suggestion 

##### Observed Behavior
The auto complete list is empty 

##### OS & Version Information
* Android Version: N/A
* SDL Android Version: 5.0.0

**Comment by JulianKast** [comment]
Fixed in #1594
