### ISSUE TITLE
Softbutton Delay 

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1600]
### Bug Report
`SoftButtonManager` takes a long time to update soft buttons on SYNC 3.0. That issue doesn't seem to be happening on Core.

##### Reproduction Steps
1. Use `SoftButtonManager` to set a set of `SoftButtons` 
2. Use the manager again to set another set of `SoftButtons` 

##### Expected Behavior
Soft button values should update quickly on HMI after setting the second `SoftButtons`

##### Observed Behavior
It takes a long time to update the values 

##### OS & Version Information
* Android Version: N/A
* SDL Android Version: 5.0.0
* Testing Against: SYNC 3.0

**Comment by JulianKast** [comment]
Fixed with #1601
