### ISSUE TITLE
Disable notifications crashes SmartDeviceLink

### ISSUE THREAD

**Issue by ArAge67** [smartdevicelink/sdl_java_suite#1621]
[Delete any non-applicable sections, but we may ask for more information or close the issue if the template is not followed. Please reference the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) for further instructions on how to enter an issue.]

### Bug Report
Following this: https://smartdevicelink.com/en/guides/android/frequently-asked-questions/sdl-notifications/ 
crashes SDL

##### Reproduction Steps
1. See bug report

##### Expected Behavior
Disable notifications

##### Observed Behavior
Crashes SDL, black screen and lock screen of phone appears

##### OS & Version Information
* Android Version: 8.0.0
* SDL Android Version: Where can I find this?
* Testing Against: I'm just a phone user

##### Test Case, Sample Code, and / or Example App
When the SmartDeviceLink notification appears, for example by using Glympse, I try to disable the notification following the manual but it causes a SDL crash.

**Comment by JulianKast** [comment]
Hello,

Thank you for reporting this issue. I have a few questions for you to assist us in our investigation.

1. What phone are you using?

2. Are you using any other apps SDL apps besides Glympse?

3. What vehicle are you connecting your phone too?

4. Do the apps connect and work before you disable notifications?

Regards,
Julian

**Comment by ArAge67** [comment]
Hi Julian,
Below you find my answers,

    What phone are you using? Samsung Galaxy A5 (2017)

    Are you using any other apps SDL apps besides Glympse? Not that I know of.

    What vehicle are you connecting your phone too? I use Glympse only for running and cycling, not for car purposes.

    Do the apps connect and work before you disable notifications? Don't know what you mean exactly. Glympse works but it doesn't have to connect to other apps (in my situation). I like to get rid of SDL or at least rid of the notifications.  

Best regards
Rene

**Comment by JulianKast** [comment]
Is your phone connected to any Bluetooth devices?

**Comment by JulianKast** [comment]
In testing, the issue did not present itself. However, we have asked the app developer to update their app to a more recent version of SDL, which we believe will resolve the issue you're experiencing. We are closing this issue, as the fix is dependent upon changes to the application, and not the SDL library.
