### ISSUE TITLE
CRC is not set for PutFile in FileManager

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1622]
### Bug Report
The `FileManager` doesn't set the `CRC` value for the file when it creates its corresponding `PutFile` RPC 

##### Expected Behavior
`FileManager` should set the CRC for every `PutFile`

##### Observed Behavior
`FileManager` is not setting the `CRC`

##### OS & Version Information
* SDL Android Version: 5.0

**Comment by JulianKast** [comment]
Fixed with #1625
