### ISSUE TITLE
Empty string bug with Menu Cell

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1623]
### Bug Report
If we set an empty string (i.e. "") for `secondaryText` or `tertiaryText`, when creating a `MenuCell` object we should send `null` instead. Otherwise core will reject the request

##### Reproduction Steps
1. Define a MenuCell
2. Set the `secondaryText` or `tertiaryText` property of `MenuCell` to an empty string (i.e. "")
3. Launch App

##### Expected Behavior
the response from core should not present any error

##### Observed Behavior
The following error is logged: 
E/BaseMenuManager: 5.0.0: Result: INVALID_DATA Info: RPC.msg_params.menuParams.secondaryText: Got string of size: 0, minimum allowed: 1

**Comment by jordynmackool** [comment]
closed via https://github.com/smartdevicelink/sdl_java_suite/pull/1624
