### ISSUE TITLE
Main Menu UI Updates Don't Take TextFieldName / ImageFieldName into account

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1628]
### Bug Report
When uploading a `MenuCell`, we need to check `menuCommandSecondaryText`, `menuCommandTertiaryText`, `menuSubMenuSecondaryText`, `menuSubMenuTertiaryText`, `menuCommandSecondaryImage`, and `menuSubMenuSecondaryImage`

##### Reproduction Steps
1. Connect to a head unit that doesn't support secondary text, tertiary text, or secondary image.
2. Attempt to send a menu cell with secondary text, tertiary text, or secondary image.

##### Expected Behavior
The unsupported text and image are not sent / uploaded.

##### Observed Behavior
The unsupported text and image are sent / uploaded.

##### OS & Version Information
* Android Version: n/a
* SDL Android Version: n/a
* Testing Against: n/a

##### Test Case, Sample Code, and / or Example App
n/a

**Comment by JulianKast** [comment]
Fixes #1629
