### ISSUE TITLE
App not sending correct capabilities back in OnAppCapabilityUpdated

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1656]
### Bug Report
`VideoStreamManager` should cache the `VideoStreamingCapabilities` received as part of the RegisterAppInterface.
The HMI might not always send the additionalCapabilities list everytime so we need to account for that.
This cached `VideoStreamingCapability` can then be used to compare to the developer defined `VideoStreamingRanges` to notify core what `VideoStreamingCapabilities` we support in an `OnAppCapabilityUpdated` notification.
The list that is sent back to core should also not contain any duplicate capabilities

##### Reproduction Steps
1. Activate app
2. Switch resolution to  480x320 via dropdown
3. Start stream on app
4. After stream starts Try to switch resolutions again

##### Expected Behavior
Resolutions list still appears

##### Observed Behavior
If later OnSystemCapabilityUpdates are sent without the additionalVideoStreamingCapabilities list
Resolutions list is empty except for 480x320

If later OnSystemCapabilityUpdates are sent with the additionalVideoStreamingCapabilities list
Resolutions list contains all supported ranges including a duplicate of 480x320

##### OS & Version Information
* SDL Android Version: 5.1_RC
* Testing Against: SDL_HMI 5.5_RC SDL_CORE 7.1_RC

**Comment by JulianKast** [comment]
Fixed with sdl_HMI release 5.1.1 : https://github.com/smartdevicelink/sdl_hmi/releases/tag/5.5.1
