### ISSUE TITLE
voiceCommand that contains no string should be removed

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1675]
### Bug Report
When a voice command contains no strings, it should not be sent in an update. Extra White space should be removed at the beginning and end of uploaded voiceCommand.

##### Reproduction Steps
1. voiceCommandA = ["    Test 1 "];
2. voiceCommandB = [];
3. Upload voiceCommands

##### Expected Behavior
currentVoiceCommands = [voiceCommandA];
voiceCommandA = ["Test 1"];

##### Observed Behavior
currentVoiceCommands = [voiceCommandA];
voiceCommandA = ["    Test 1 "];
Error message is printed to logs.

**Comment by theresalech** [comment]
Corresponding issues: [iOS](https://github.com/smartdevicelink/sdl_ios/issues/1964), [JavaScript Suite](https://github.com/smartdevicelink/sdl_javascript_suite/issues/431)

**Comment by JulianKast** [comment]
fixed with #1686
