### ISSUE TITLE
java.lang.NegativeArraySizeException Crash at SdlPsm.java line 241 com.smartdevicelink.transport.SdlPsm.transitionOnInput

### ISSUE THREAD

**Issue by asheeshs** [smartdevicelink/sdl_java_suite#1678]
### Bug Report
Fatal Crash 
```
Fatal Exception: java.lang.NegativeArraySizeException: -592969471
       at com.smartdevicelink.transport.SdlPsm.transitionOnInput(SdlPsm.java:241)
       at com.smartdevicelink.transport.SdlPsm.handleByte(SdlPsm.java:88)
       at com.smartdevicelink.transport.MultiplexBluetoothTransport$ConnectedThread.run(MultiplexBluetoothTransport.java:801)

```

##### Reproduction Steps
Seeing crash in Firebase Crashlytics dash, unfortunately no reproduction steps to share. 

##### Expected Behavior
No Crash

##### Observed Behavior
Crashing

##### OS & Version Information
* Android Version: 46% Android 11, 45% Android 10, 5% Android 7%
* SDL Android Version: 4.12.0
* Testing Against: 
According to crash logs. app was always in background when the crash was seen.

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by JulianKast** [comment]
fixed with #1683
