### ISSUE TITLE
Primary Graphic not sent to SDL Core for Media Template 

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1690]
### Bug Report
Primary Graphic and text updated using Screen Manager, however only text gets updated

##### Reproduction Steps
- Connect a media app, it will start on the media template
- Change the layout to something else, like textAndGraphic
- Change the layout back to MEDIA
- Try to show another image.
- The display capabilities that are returned don’t include that the primary graphic is supported, so it will fail.

##### Expected Behavior
Text and graphic should be updated

##### Observed Behavior
Only text is updated. Screen manager somehow determines that there is no image to update.

##### OS & Version Information
SDL Java Suite Version: 5.1.1
Testing Against: Ford SYNC 3.0

**Comment by JulianKast** [comment]
fixed by #1694
