### ISSUE TITLE
Lockscreen should show again after dismissal if a DD notification is received where DismissalEnabled is false

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_java_suite#1695]
### Bug Report
There is an edge case for the lockscreen where we want to be able to show the lockscreen to the user again even if the user has previously dismissed the lockscreen.

##### Reproduction Steps
1. Lockscreen displayMode = ALWAYS
2. The last DriverDistraction notification received was `DD_OFF` and that `lockScreenDismissalEnabled = true`
3. The user should be shown a dismissable lockscreen
4. The user dismisses the lockScreen
5. Another DriverDistraction notification is received with `DD_ON` and `lockScreenDismissalEnabled=false`

##### Expected Behavior
The lockscreen should be launched again without a dismiss message

##### Observed Behavior
The lockscreen should doesn't get launched

##### OS & Version Information
* Android Version: N/A
* SDL Android Version: 5.1.1
* Testing Against: Core 7.1.1/ Generic HMI 0.10.0

**Comment by JulianKast** [comment]
Fixed with #1699
