### ISSUE TITLE
Handler instances using deprecated constructors  

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_java_suite#1696]
### Bug Report
As of Android SDK 30 the no parameter and callback constructors of the `Handler` class were deprecated. Now a `Looper` instance is required to be passed. The library uses the default,no param constructor in most cases.

See here: https://developer.android.com/reference/android/os/Handler#Handler()

##### Expected Behavior
The library does not use deprecated methods from the Android API.

##### Observed Behavior
The library uses deprecated constroctures for `Handler` instances

##### OS & Version Information
* Android Version: SDK 30
* SDL Android Version: 5.1.1

###### Two solutions are possible:

**Update handler constructors**

```java
Handler handler = new Handler();
```

Needs to be replaced with

```java
Handler handler = new Handler(Looper.getMainLooper());
```

**Switch to using TaskMaster**

Replace `Handler` with a queue from task master and create tasks to be used. This solution will not work in the cases where a `Handler` is passed to a Messenger instance, for example the binding between `TransportBroker` and `SdlRouterService
`.

**Comment by JulianKast** [comment]
Closed via #1726
