### ISSUE TITLE
Sdl disconnection is not notified to the app

### ISSUE THREAD

**Issue by kalaiselvan369** [smartdevicelink/sdl_java_suite#1697]
### Needs Enchancement
When the connection is explicitly ended from the in-vehicle system(for example turning off the infotainment device or its bluetooth) then the android app which is running SDL service doesn't receive any connection destroyed/sdl disabled callback hence the service doesn't terminate in the app. In this scenario what we would except is some kind of broadcast from `SdlBroadcastReceiver` base class which will disable the service like the way it used to start the SDL service using onSdlEnabled callback.

##### Reproduction Steps
1. Connect the mobile app to the infotainment system or simulator via bluetooth.
2. Now turn off the infotainment system or simulator.
3. In android app you will notice that SDL service is still running and the notification is shown in notification bar.

##### Expected Behavior
1. When we turn off the infotainment screen or simulator, we should have callback `onSdlDisabled` from `SdlBroadcastReceiver` like we currently have `onSdlEnabled` method which is starting the SdlService.

##### OS & Version Information
* Android Version: 10
* SDL Android Version: 5.1.1

##### logs
I am using the sdl_java_suite android sample. Here is the log I captured when I turned off the infotaintment screen or simulator.

```
`I/RpcConverter: 5.1.1: name  -  OnAppInterfaceUnregistered

I/RpcConverter: 5.1.1: parameters  -  {reason=IGNITION_OFF}

I/RpcConverter: 5.1.1: correlationID  -  -1

I/RpcConverter: 5.1.1:  Attempting to create com.smartdevicelink.proxy.rpc.OnAppInterfaceUnregistered

I/Lifecycle Manager: 5.1.1: RPC received - notification

I/Lifecycle Manager: 5.1.1: on app interface unregistered

I/SdlTransportBroker: 5.1.1: Stopping transport broker for com.sdl.android.8678309.03460023

I/SdlTransportBroker: 5.1.1: Attempting to unregister with Sdl Router Service

I/Lifecycle Manager: 5.1.1: onRPCNotificationReceived - OnAppInterfaceUnregistered

I/Lifecycle Manager: 5.1.1: on protocol session ended

I/SdlTransportBroker: 5.1.1: Hardware disconnected

I/TransportManager: 5.1.1: Transport disconnected - Transport Type: BLUETOOTH Address: 34:18:C3:11:05:DC

W/SdlTransportBroker: 5.1.1: Unregister request denied from router service. Reason - 1`
```

Please let me know if this issue already exists and if there is any enhancement in progress. Also share if there is any work around to get notified about the SDL disconnection so that I can disable/stop the service which running.

**Comment by joeygrover** [comment]
This appears to be an issue of when the IVI sends the `OnAppInterfaceUnregistered` before the transport disconnects. In most production vehicles the transport is disconnected prior to being able to send that notification from the IVI to the library. When the `OnAppInterfaceUnregistered` is received the library closes everything but the `TransportManager` has a flag that prevents the `onTransportDisconnected` callback from happening since it was manually told to close the transport. This should be an easy fix.
