### ISSUE TITLE
Race condition leads to NPE in TransportManager

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_java_suite#1703]
### Bug Report

There is a race condition that exists in the `TransportManager` class of the Android project when the app is in legacy mode. If the user requests a close of the app or the `SdlService` is shutdown and the `SdlManager` closes the transport layer, there is a chance that the local bluetooth broadcast receiver also receives a disconnect intent which causes two different parts of code to close the legacy mode transport and set it to null.

See:

https://github.com/smartdevicelink/sdl_java_suite/blob/65c43df37ac13ca650a5548efd4c87a65a90d8cf/android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java#L121-L124

and:

https://github.com/smartdevicelink/sdl_java_suite/blob/65c43df37ac13ca650a5548efd4c87a65a90d8cf/android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java#L432-L436

##### Reproduction Steps

This is a near impossible bug to reproduce reliability so the code paths will have to be trusted, however we have seen this issue reported by app partners. See #1213  &  #1412 

##### Expected Behavior
While any form of disconnection is happening the transport layer should shut down gracefully and not report out any crashes.

##### Observed Behavior
The transport layer does close down, however, an NPE exception is being thrown.

**Comment by JulianKast** [comment]
Fixed with #1704
