### ISSUE TITLE
Security queries are not implemented to spec

### ISSUE THREAD

**Issue by jacobkeeler** [smartdevicelink/sdl_java_suite#1720]
### Bug Report
With the acceptance of [SDL 0317](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0317-sdl-protocol-security-specification.md), this library's implementation of security queries does not match the spec fully. Several issues exist with the current implementation such as:

1. When a security query is received from Core, its header is entirely ignored and the library assumes that it is a `Send Handshake Data` request. This causes issues if Core were to send another type of query, such as a `Send Internal Error` notification.

```java
        System.arraycopy(msg.getData(), 12, data, 0, iLen);

        byte[] dataToRead = new byte[4096];

        Integer iNumBytes = sdlSecurity.runHandshake(data, dataToRead);
```

2. Hardcoded values are used when sending security queries for fields such as query ID. In addition, some values are not explicitly set at all, such as query type and sequential number. Any predefined values should be properly added as constants.

```java
        protocolMessage.setFunctionID(0x01);
```

should be changed to something like

```java
        securityQuery.setQueryID(QueryID.SEND_HANDSHAKE_DATA);
        securityQuery.setQueryType(QueryType.RESPONSE);
        securityQuery.setSequenceNumber(msg.getSequenceNumber());
```

3. Security queries are constructed using an RPC header, which has a slightly different format than a security query header. Security query headers should be implemented separate from RPC headers.

```java
        ProtocolMessage protocolMessage = new ProtocolMessage();
        ...
        sendMessage(protocolMessage);
```

should be changed to something like

```java
        SecurityQuery securityQuery = new SecurityQuery();
        ...
        sendMessage(securityQuery);
```

##### OS & Version Information
* Android Version: N/A
* SDL Android Version: master
* Testing Against: N/A

**Comment by theresalech** [comment]
See Core issue https://github.com/smartdevicelink/sdl_core/issues/3755; the mobile libraries will need to account for this by accepting both the NOTIFICATION and REQUEST types for SendHandshakeData and just treating them as REQUEST type.
