### ISSUE TITLE
Bluetooth Permission Requirements will change in Android 12

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_java_suite#1732]
### Bug Report
Starting with android 12 new Bluetooth Runtime permissions are required. The `MultiplexBluetoothTransport` class will require the new `BLUETOOTH_SCAN` and `BLUETOOTH_CONNECT` Permissions

https://developer.android.com/about/versions/12/features/bluetooth-permissions

##### OS & Version Information
* Android Version: SDK 31

**Comment by joeygrover** [comment]
Fixed in #1771
