### ISSUE TITLE
Jizzle

### ISSUE THREAD

**Issue by Jizzle6921** [smartdevicelink/sdl_java_suite#1765]
sudo apt-get install git cmake build-essential sqlite3 libsqlite3-dev libssl-dev libssl1.1 libusb-1.0-0-dev libudev-dev libgtest-dev libbluetooth3 libbluetooth-dev bluez-tools libpulse-dev python3-pip python3-setuptools python3-wheel python

cd sdl_core git submodule init git submodule updategit clone

**Comment by joeljfischer** [comment]
Hello, I'm not sure what this issue on the java suite is intended for, so it will be closed. If you have other concerns, please place a comment.
