### ISSUE TITLE
`userDidSubmitInput` getting called multiple times after a search request is submitted

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1768]
### Bug Report
When the user submits a search request through a searchableChoiceSet, the userDidSubmitInput keyboard's listener method gets called multiple times when updateAutocomplete method is implemented

##### Reproduction Steps
1. Present a searchable choice set
2. Submit a search through the search box in choiceset or click on an autocomplete cell

##### Expected Behavior
userDidSubmitInput method gets called once per key input

##### Observed Behavior
userDidSubmitInput method gets called multiple times per key input

##### OS & Version Information
* Android Version: 11
* SDL Android Version: 5.3.0
* Testing Against: Sdl_hmi, core 8.0.0

**Comment by RHenigan** [comment]
This issue was fixed and resolved in the [5.3.1 Hotfix release](https://github.com/smartdevicelink/sdl_java_suite/releases/tag/5.3.1).
As part of PR #1773
