### ISSUE TITLE
Android - Declaring custom permissions for SDL services crashes other apps when opened

### ISSUE THREAD

**Issue by kalaiselvan369** [smartdevicelink/sdl_java_suite#1770]
### Clarification or Support Needed
I have developed a sample android app which uses SDL library(v5.2.0) for a feature that receives vehicle metrics from the car via Bluetooth. In order to secure the app's SDL related services, I have added a custom permission in the android manifest file. Correspondingly, I have also set this permission to `SdlRouterService`, `SdlService` service tag as well. The objective is to secure these services so that others apps on the device cannot access it.  Now I launched my sample app and it worked as expected(Connected to car headunit via Bluetooth). Parallely when I opened Cisco Webex app, the webex app keep crashing. Similary crash happens when I open any other app which uses SDL lib internally.

#### AndroidManifest.xml

```  
       <permission
        android:name="com.sdl.hellosdlandroid.permissions.SYNC3"
        android:protectionLevel="signature" />

        <service
            android:name="com.sdl.hellosdlandroid.SdlService"
            android:permission="com.sdl.hellosdlandroid.permissions.SYNC3"
            android:foregroundServiceType="connectedDevice">
        </service>
        <service
            android:name=".SdlRouterService"
            android:exported="true"
            android:permission="com.sdl.hellosdlandroid.permissions.SYNC3"
            android:process="com.smartdevicelink.router"
            android:foregroundServiceType="connectedDevice">
            <intent-filter>
                <action android:name="com.smartdevicelink.router.service" />
            </intent-filter>
            <meta-data
                android:name="@string/sdl_router_service_version_name"
                android:value="@integer/sdl_router_service_version_value" />
        </service>
```

##### Crash logs capture at the time of cisco webex app crash

` Caused by: java.lang.SecurityException: Not allowed to start service Intent { cmp=com.sdl.hellosdlandroid/.SdlRouterService (has extras) } without permission com.sdl.hellosdlandroid.permissions.SYNC3
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1680)
        at android.app.ContextImpl.startForegroundService(ContextImpl.java:1638)
        at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:688)
        at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:688)
        at com.smartdevicelink.transport.SdlRouterStatusProvider.bindToService(SourceFile:8)
        at com.smartdevicelink.transport.SdlRouterStatusProvider.checkIsConnected(SourceFile:1)
        at com.smartdevicelink.transport.SdlBroadcastReceiver$5.onListObtained(SourceFile:1)
        at com.smartdevicelink.transport.RouterServiceValidator.createTrustedListRequest(SourceFile:23)
        at com.smartdevicelink.transport.RouterServiceValidator.createTrustedListRequest(SourceFile:3)
        at com.smartdevicelink.transport.SdlBroadcastReceiver.requestTransportStatus(SourceFile:8)
        at com.smartdevicelink.transport.SdlBroadcastReceiver.access$200(SourceFile:1)
        at com.smartdevicelink.transport.SdlBroadcastReceiver$3.onComplete(SourceFile:3)
        at com.smartdevicelink.util.ServiceFinder.onFinished(SourceFile:2)
        at com.smartdevicelink.util.ServiceFinder.access$000(SourceFile:1)
        at com.smartdevicelink.util.ServiceFinder$2.onReceive(SourceFile:10)`

##### Reproduction Steps
1. In the existing SDL sample app declare custom permission with protection level to signature. Also make both SDL services to abide by this permission.
2. Next, Install Cisco webex app or another sample app which uses SDL library internally.
3. Now launch your sample app. Make sure it get's connected to car headunit or simulator via Bluetooth. Then open cisco webex app or another sample app which uses SDL library. 
4. You will now notice that Cisco webex app or another sample app keep crashing.

##### Expected Behavior
I was expecting that each app which uses SDL library internally for its feature would have their own `SdlRouterService` implementation. Obviously, those apps should be using their own router services only if they are trying to connect to car or simulator.

##### Observed Behavior
In my case other apps which uses SDL lib internally is trying to access my sample app's router service. Since I have declared a custom permission for my router services, the other apps which is trying to access it are getting crashed with the Security Exception.

1. Why would other apps access my `SdlRouterService` implementation although they have one?
2. Does this happen due to android:process="com.smartdevicelink.router" declared in the SdlRouterService?

#### Questions
1. Is it advisable to use custom permissions like this? 

I had to try this method(declaring custom permissions) because the app security testing team are asking for protecting level of these services.

##### OS & Version Information
* Android Version: 10
* SDL Android Version: 5.2.0
* Testing Against: Simluator and Car

##### Test Case, Sample Code, and / or Example App
I have added a sample snippet of Android Manifest file above.

**Comment by joeygrover** [comment]
Closing as not an issue.

[Per the documentation](https://smartdevicelink.com/en/guides/android/frequently-asked-questions/trusted-router-service/#what-is-the-android-router-service): 

>### What is the Android Router Service?
>The Android OS has limitations around the availability of certain transports (Bluetooth RFCOMM channels, single app AOA/USB permissions). Therefore, SmartDeviceLink (SDL) introduced a service that operates as a router, using a single transport pipe and extending it to many different bound apps. The router service is part of the required integration to become SDL enabled and can be hosted by any of the SDL enabled apps on a phone. Some OEMs might choose to have their own companion app that always hosts a router service for their specific hardware.


This means that there is only ever one instance of the SDL Router Service running on the mobile device. So while each application contains the library and implementation of the service, only one app spins it up and other apps bind to it. Developers are not allowed to alter the contents of the `SdlRouterService` class if they wish to pass certification. Other applications have the ability to check and see if the hosted router service is trusted or not before they bind. So adding a custom permission will cause the crash as expected and therefore is not allowed for the `SdlRouterService`.

You are more than welcomed to add a custom permission to your own `SdlService` however if it is not exported then I do not believe it guarantees much more security.

**Comment by kalaiselvan369** [comment]
Thank you @joeygrover  for the info.
