### ISSUE TITLE
[SDL 0345] Android 12 Issues

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#1794]
### Proposal Link

Proposal: [Android 12 Issues](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0345-android-12-issues.md)

### Proposal Introduction

>With almost every Android version, Google updates the OS to better distribute the device resources among the running apps to enhance the performance and optimize battery life. However, sometimes the new enhancements come with new restrictions on how apps can use the resources on the device. Android 12 is one of the major Android updates that heavily modify how apps can run in the background and use device resources. This affects how the `SdlRouterService` starts and communicates with other SDL apps and also how the `SdlService` for SDL apps is started. This proposal is to address the issues that have been introduced as a result of Android 12.

### Review Link

Review: https://github.com/smartdevicelink/sdl_evolution/issues/1181

**Comment by joeygrover** [comment]
Fixed in #1771
