### ISSUE TITLE
Attempting to Send Voice Command with No Strings Fails to Log Error

### ISSUE THREAD

**Issue by noah-livio** [smartdevicelink/sdl_java_suite#1798]
### Bug Summary

When trying to send a `VoiceCommand` containing no command strings using `VoiceCommandManager`, it fails to send as expected, but no error is logged to explain this behavior to the app developer.

### Reproduction Steps

1. Create `VoiceCommand` containing no command strings
2. Attempt to send the `VoiceCommand` to an HMI using `VoiceCommandManager`
3. Observe debug logs

Expected Behavior: The `VoiceCommand` fails to send and an error is logged

Observed Behavior: The `VoiceCommand` fails to send and no error is logged

### Which projects have you seen this bug on?

Android, Java Standard Edition

### Android Version(s)

12

### Android Device(s)

Samsung Galaxy S21 5G

### sdl_java_suite Version

5.4.0_RC

### Testing Environment(s)

```markdown
- Ford TDK 3.4 (19353_DEVTEST_r133796)
- SDL Core v7.1.1 SDL HMI 5.5.1
- SDL Core v8.1.1 SDL HMI 5.7
```

### Relevant log output

```shell
N/A
```

**Comment by JulianKast** [comment]
Fixed with #1799
