### ISSUE TITLE
Incorrect behavior and potential crashes in PresentAlertOperation.supportsSoftButtonImages()

### ISSUE THREAD

**Issue by noah-livio** [smartdevicelink/sdl_java_suite#1800]
### Bug Summary

`PresentAlertOperation.supportSoftButtonImages()` has the potential to crash under the following circumstances:

- `currentWindowCapability` is null, causes `NullPointerException`
- `currentWindowCapability.getSoftButtonCapabilities()` is null, causes `NullPointerException`
- `currentWindowCapability.getSoftButtonCapabilities()` has a length of zero, causes `IndexOutOfBoundsException`
- `currentWindowCapability.getSoftButtonCapabilities().get(0)` is null, causes `NullPointerException`

Additionally, under these circumstances, instead of crashing,`PresentAlertOperation.supportSoftButtonImages()` should return true because `SoftButtonImage`s are supposed to be supported by default when the capability is missing.

### Reproduction Steps

N/A, this issue does not come from a direct crash report, but was discovered during alignment checking related to [sdl_javascript_suite issue #526](https://github.com/smartdevicelink/sdl_javascript_suite/issues/526)

### Android Version(s)

N/A

### Android Device(s)

N/A

### sdl_java_suite Version

5.4.0_RC

### Testing Environment(s)

```markdown
N/A, not discovered during testing
```

**Comment by JulianKast** [comment]
Fixed with #1801
