### ISSUE TITLE
Media app does not disappear from Sync after bluetooth connection is turned off when USB is plugged in if the app RequiresAudioSupport flag is set to true

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1802]
### Bug Summary

Media app does not disappear from Sync after bluetooth connection is turned off when USB is plugged in if the app RequiresAudioSupport flag is set to true. Happens most of the time.

### Reproduction Steps

1. Set test app to Media using multiplexing
2. Turn off bluetooth adapter
3. Connect AOA through multiplexing, observe test app did not register
4. Turn on bluetooth and allow to connect to device
5. If app does not register automatically, open the manually and observe it did register
6. Turn off bluetooth adapter, observe app unregisters

Expected Behavior:
App unregisters and does not appear on Sync
Observed Behavior:
App sometimes appears on Sync, but is unusable

### Android Version(s)

9. 11, 12

### Android Device(s)

Pixel 3, Pixel 4a, Samsung galaxy s8+

### sdl_java_suite Version

5.4.0, 5.3.1

### Testing Environment(s)

```markdown
Sync 3.0
```

**Comment by theresalech** [comment]
Closed via #1827
