### ISSUE TITLE
sdl_java_se uses deprecated testCompile in build.gradle

### ISSUE THREAD

**Issue by noah-livio** [smartdevicelink/sdl_java_suite#1805]
### Bug Summary

Using testCompile has the potential to make grade sync fail on newer Gradle and Java versions.

### Reproduction Steps

N/A

### Which projects have you seen this bug on?

Java Standard Edition

### sdl_java_suite Version

5.4.0_RC

### Testing Environment(s)

```markdown
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by JulianKast** [comment]
Fixed with #1806
