### ISSUE TITLE
API Reference Documentation Tables are broken  

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_java_suite#1817]
### Bug Summary

Broken tables exist on the listed pages within the API Reference Documentation. 

### Reproduction Steps

Expected Behavior:
It is expected that the tables do not continue throughout the documentation page. 

Observed Behavior: See broken tables on the following pages: 

- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/AddCommand/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/AddSubMenu/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/BodyInformation/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/GetVehicleData/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/KeyboardProperties/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/MenuParams/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/OnVehicleData/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/SetMediaClockTimer/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/Show/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/SubscribeVehicleData/
- https://www.smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/UnsubscribeVehicleData/

### Android Version(s)

N/A

### Android Device(s)

N/A

### sdl_java_suite Version

N/A

### Testing Environment(s)

```markdown
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by joeljfischer** [comment]
Closed by #1810
