### ISSUE TITLE
SdlArtwork clone issue

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1818]
### Bug Summary

If you use the clone method in SdlArtwork to clone an artwork, then change the name of the cloned artwork and upload it using the TextAndGraphic manager, the name that is uploaded with the file in the FileManager is different then the one sent in the imageRPC in the show in TextAndGraphicManager causing it to fail.

### Reproduction Steps

1. Clone an SdlArtwork opject
2. Change name of SdlArtwork object
3. Set primary graphic using cloned image with TextAndGraphicManager. 

Expected Behavior:

Image should be displayed on screen

Observed Behavior:
Image is not displayed on screen. Name sent in FileManager upload is the new name set for the artwork but name sent in show in TextAndGraphicManager in imageRPC is old name of artwork. I believe the issue is with the cloning method where we create the imageRPC(even if one hasn't been created yet)

### Android Version(s)

12

### Android Device(s)

Pixel 4a

### sdl_java_suite Version

5.4.0

### Testing Environment(s)

```markdown
Sync
```

**Comment by joeljfischer** [comment]
Fixed by #1821
