### ISSUE TITLE
Some API Reference Documentation Does Not Match RPC Spec

### ISSUE THREAD

**Issue by noah-livio** [smartdevicelink/sdl_java_suite#1819]
### Bug Summary

Some API Reference Documentation tables I saw while reviewing #1810 have information that does not match the [RPC Spec](https://smartdevicelink.com/en/guides/sdl-overview-guides/rpc-spec/).

List of affected classes and their discrepancies:

- AddCommand
	
	- `menuParams` is of type `MenuParams` in spec and code, but `ButtonName` in documentation
	- `menuParams` is mandatory in documentation, but not in spec
	- `vrCommands` is `String[]` in spec, `List<String>` in code, and `String` in documentation

- AddSubMenu

	- `menuLayout` is optional in spec and mandatory status is missing in documentation

- BodyInformation

	- `parkBrakeActive` is listed twice in documentation

- MenuParams

	- `parentID`, `position`, and `menuName` are missing mandatory status in documentation

- OnVehicleData
	
	- `fuelLevel` is `Float` in spec, `Double` in code, and `Boolean` in documentation
	- `fuelLevel_State` is `ComponentVolumeStatus` in spec and code, and `Boolean` in documentation
	- `fuelRange` is `FuelRange[]` in spec, `List<FuelRange>` in code, and `Boolean` in documentation
	- `windowStatus` is `WindowStatus[]` in spec, `List<WindowStatus>` in code, and `Boolean` in documentation

- Show

	- `softButtons` is `SoftButton[]` in spec, `List<SoftButton>` in code, and `SoftButton` in documentation

### Reproduction Steps

N/A

### Which projects have you seen this bug on?

Android, Java Standard Edition

### Android Version(s)

N/A

### Android Device(s)

N/A

### sdl_java_suite Version

5.4.0+

### Testing Environment(s)

```markdown
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by JulianKast** [comment]
Fixed with #1820
