### ISSUE TITLE
Setting bad data in one T&G field then good data quickly in another can lead to the good data failing.

### ISSUE THREAD

**Issue by ChloeMJM** [smartdevicelink/sdl_java_suite#1828]
### Bug Summary

This bug is related to iOS Issue #[1781](https://github.com/smartdevicelink/sdl_ios/issues/1781)

Based on how the Text & Graphic manager currently works, it is possible to have good data fail. A possible solution is that when a `Show `fails and the `currentScreenData `gets updated to also update the `updateState` of the T&G operation as well. This will require knowing which fields the T&G operation is updating so that they don't also get reset.

With a similar method we could potentially also stop sending all Show data and only send updated Show data.

### Reproduction Steps

1. Set "bad" data (data that will get rejected) into `TextField1` and start the operation.
2. Set "good" data (data that will not get rejected) into `TextField2` and start the operation before the first operation gets a Show response.

Expected Behavior: `TextField1 `should remain in its original state and `TextField2` should show the new data.

Observed Behavior: `TextField1` and `TextField2` will show the original state data because `TextField2`'s operation includes the `TextField1` data as well.

### Android Device(s)

n/a

### sdl_java_suite Version

5.5.0

### Testing Environment(s)

```markdown
Manticore
```

**Comment by JulianKast** [comment]
Fixed with #1833
