### ISSUE TITLE
SdlRouterService doesn't include PendingIntent for ping broadcasts

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_java_suite#1843]
### Bug Summary

The RS does not include its pendingIntent for apps to start their SdlServices. This is an issue if the app is installed during an already connected session. That would happen also if an app crashed and was restarted during a connected session.

### Reproduction Steps

1. Install app after RS is already connected

Expected Behavior:
Installed app connects to RS and IVI

Observed Behavior:
App does not start its SdlService and therefore does not connect

### Which projects have you seen this bug on?

Android

### sdl_java_suite Version

5.6.1

### Testing Environment(s)

```markdown
N/A
```

**Comment by mrapitis** [comment]
@jordynmackool would it be possible to prioritize this ticket in a future bug fix release?

**Comment by joeygrover** [comment]
It is being worked on.

**Comment by JulianKast** [comment]
Fixed with #1844
