### ISSUE TITLE
`RemoteServiceException ForegroundServiceDidNotStartInTimeException` for SdlService

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1848]
### Bug Summary

Since we start SdlServices from the RS with the pending intent it is now likely that there could be a potential remote exception of the SdlService not calling startForeground in time. We should add that exception to the handler and keep it moving.

### Reproduction Steps

1. Connect SDL app normailly via Bluetooth on Androud 12+ device
2. Download and install a second SDL app that SdlService will not call to start the foreground.

Expected Behavior:
We would like for the SdlBroadcast receiver's uncaught exception handler to handle it and keep moving.
Observed Behavior:
App crashes, and we get an ANR

### Android Version(s)

12+

### Android Device(s)

Pixel 4a

### sdl_java_suite Version

5.6.1

### Testing Environment(s)

```markdown
Sync 3.0
```

**Comment by joeygrover** [comment]
Closed with #1849
