### ISSUE TITLE
Update SDL Library for Android 14

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1856]
### Description

With Android 14 there are several changes that need to be made to the SDL library for it to work on an Android 14 device, as well as be able to have apps target API level 34.

**Comment by shiniwat** [comment]
Hi @JulianKast,
We are working on our product to support Android 14 and API level 34, and recognize SDL library must be updated too.
As I understand, SDLC plans to release updated sdl_java_suite version (maybe 5.7?) that support Android 14 and API level 34. 
When do you plan to release updated sdl_java_suite? Looks like 5.6.2 (bug fix release) is being prepared, but 5.6.2 does not seem to have Android 14 support.

**Comment by JulianKast** [comment]
HI, I am actively working on supporting Android 14 for the sdl library. Our next release will be 5.7.0. We will start our release process once we have finalized Android 14 support, I don't know when that will be exactly.

**Comment by shiniwat** [comment]
Hi @JulianKast 
I understand 5.6.2 is being prepared at https://github.com/smartdevicelink/sdl_java_suite/projects/25, and all required Android 14 support is planned in 5.6.2.
Can you please tell us the plan about 5.6.2? In particular, when will it be released?

**Comment by JulianKast** [comment]
Hi @shiniwat, instead of 5.6.2, we just got to work on 5.7.0 and released it today. Sorry I missed your comment

**Comment by JulianKast** [comment]
Android 14 is now supported with release [5.7.0](https://github.com/smartdevicelink/sdl_java_suite/releases/tag/5.7.0)
