### ISSUE TITLE
Bluetooth notification error when phone disconnects from Bluetooth

### ISSUE THREAD

**Issue by JulianKast** [smartdevicelink/sdl_java_suite#1867]
### Description

It is reported that the notification for "Too many apps are using Bluetooth" appears randomly when users are disconnecting from their car.

Upon further investigation, I have determined that it happens when we reach BluetoothSocket channel 30 and disconnect from the car.

Steps to reproduce:
1. Install SDL app to phone
2. Connect to tdk via Bluetooth
3. Observe SDL app connection
4. Disconnect from tdk by clicking on the BT connection and clicking disconnect on the phone.
5. Repeat steps 2-4 up to 30 times until a notification appears that says "Too many apps are using Bluetooth"

**Comment by joeygrover** [comment]
Closed with #1868
