### ISSUE TITLE
Null Pointer Exception in SdlRouterService.getNextTask

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_java_suite#1869]
### Bug Summary

We have captured a null pointer exception in SdlRouterService.getNextTask. The issue has been captured via the Play console and occurs regularly, however I have been unable to reproduce the issue on the bench thus far.  Please find crash log below for additional details:

``` 
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Collection java.util.HashMap.values()' on a null object reference
  at com.smartdevicelink.transport.SdlRouterService.getNextTask (SdlRouterService.java:2945)
  at com.smartdevicelink.transport.SdlRouterService$PacketWriteTaskMaster.run (SdlRouterService.java:3705) 
```

### Reproduction Steps

Expected Behavior:
No null pointer exception crash in getNextTask
Observed Behavior:
Null pointer exception crash in getNextTask

### Which projects have you seen this bug on?

Android

### sdl_java_suite Version

5.6.1

### Testing Environment(s)

```markdown
Ford Headunits in field
```

**Comment by joeygrover** [comment]
Closed with #1870
