### ISSUE TITLE
IntegrationValidator is missing newer permission requirements

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_java_suite#1874]
### Bug Summary

The `IntegrationValidator` is missing a few of the newer permission requirements. They should be added to ensure that integrations are completed successfully. 

### Reproduction Steps

1. Don't include a newer permission in the manifest
2. Deploy debug build of app 
3. Connect over BT with IVI

Expected Behavior:
`IntegrationValidator` reports the missing permission

Observed Behavior:
`IntegrationValidator` does not report the missing permissions

### Which projects have you seen this bug on?

Android

### Android Version(s)

14.0.0

### Android Device(s)

Pixel 5a

### sdl_java_suite Version

5.x.0 (develop)

### Testing Environment(s)

```markdown
N/A
```

**Comment by JulianKast** [comment]
Fixed with #1875
