### ISSUE TITLE
SdlDeviceListener should be activated even with no device and more than one app

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_java_suite#1878]
### Bug Summary

The current logic in the `SdlBroadcastReceiver` only allows the `SdlDeviceListener` to start when there isn't a BT device if the current app is the only app installed. The thought was that it would mean an app was already installed and should have caught the BT connection initially so therefore it wouldn't need to run again. However, there is another scenario where it would be beneficial to start the `SdlDeviceListener` after the initial connection. If the first connection window was missed by the IVI, when the user opens up an SDL enabled application it should run a query for running router services and if one doesn't exist try to create another connection. So the check against being the only app should be removed so that we can attempt to create another connection successfully. 

### Reproduction Steps

1. Connect BT with a device with an SDL app installed
2. Allow the RS service to timeout for the connection
3. Open the app again and select "Find new apps"

Expected Behavior:
The IVI is able to establish the first SPP connection which prompts the RS notification to appear on the phone. 

Observed Behavior:
The app is not able to connect until the BT connection is disconnected and reconnected. 

### Which projects have you seen this bug on?

Android

### Android Version(s)

14.0.0

### Android Device(s)

Pixel 5a

### sdl_java_suite Version

5.x.0 (develop)

### Testing Environment(s)

```markdown
Ford TDK
```

**Comment by JulianKast** [comment]
Fixed with #1879
