### ISSUE TITLE
DiagLevel NullPointerExceptions

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_java_suite#195]
> _com/smartdevicelink/trace/DiagLevel_

`NullPointerException` is thrown by the following methods int the [DiagLevel](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/trace/DiagLevel.java) test class.

``` java
try {
    // Invalid/Null Tests
    assertFalse(Test.FALSE, DiagLevel.isValidDetailLevel(testInvalidS));
    assertFalse(Test.FALSE, DiagLevel.isValidDetailLevel(null)); // Exception here
    assertNull(Test.NULL, DiagLevel.getLevel(null)); // Exception here
    DiagLevel.setLevel(null, null); // Exception here
    DiagLevel.setAllLevels(null); // Exception here
} catch (NullPointerException e) {
    fail("NullPointerException was thrown when attempting to set null values.");
}
```

Solution : The methods should verify that the parameters are not null before attempting to manipulate the data.

**Comment by bilal-alsharifi** [comment]
Fixed in this commit https://github.com/smartdevicelink/sdl_java_suite/commit/19363b7b89621d4cfd0b571734fd112fcfbd3af1
