### ISSUE TITLE
Policy Url Testing

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_java_suite#219]
These items are labeled as 'for testing only'. Should they now be removed, if that testing is done?

``` java
private String sPoliciesURL = ""; //for testing only

...

String sURLString;
if (!getPoliciesURL().equals(""))
    sURLString = sPoliciesURL;
else
    sURLString = msg.getUrl();

...

//for testing only
public void setPoliciesURL(String sText)
{
    sPoliciesURL = sText;
}
//for testing only
public String getPoliciesURL()
{
    return sPoliciesURL;
}
```

**Comment by justinjdickow** [comment]
The methods for setting the testing variable should be removed for 4.0.0 because the sendOnSystemRequestToUrl method will use the sPoliciesURL string if the developer chooses to set it to anything other than "".

**Comment by JulianKast** [comment]
This coed resided in `SdlProxyBase` which was removed for our 5.0 release with this PR #1471
