### ISSUE TITLE
SdlTrace Questions & Issues

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_java_suite#220]
There are many things in the [SdlTrace](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java) class that either raise questions or issues, so this is my detailed breakdown to highlight both.
#### **IMPORTANT QUESTION:** Is the purpose of the XML encoding in the SdlTrace class for Siphon Server logging only?

_Clarification_: Logging XML encoded messages to the native Android log tool does not make any sense, messages should be plain and easy to read. The [ISTListener](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/trace/ISTListener.java) class is essentially an unknown entity controlled by the developer, for what reason would there be to receive an XML encoded log message? Why encode it at all?

**Answer: Yes, but developers may also be using it if they have been given the same decoding tool. So until this is looked into further, encoding can't be completely removed.**

_Comment: Perhaps it can be made a legacy support feature, but it would still be much nicer to be able to remove it and all of it's overhead entirely and have this information provided in an easier to read format instead. If it is dependent on a decoding key then it is developer-discriminating and should probably not be in the library._

@joeygrover @mrapitis 

If yes, then most of the changes listed below can be ignored and a massive amount of code can be removed or deprecated from not only this class, but several others as there is a lot of overhead needed.

If no, carry on reading.

---

Backwards Compatible :+1:
### **(1) Scope**

``` java
// Package-scoped
```

Comments like this appear before several methods in the [SdlTrace](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java) class, but it is not a true statement for all the methods it precedes.

For methods like `getBaseTicsDelta()` and `getBaseTics()` that have no scope modifier specified the default access level is "package-private", meaning that these methods can be accessed (or called) from all classes within the same package including the class it is defined in, but not globally or from any subclasses.

However, for the `getLogHeader(String, int)` method this is not true because it is specified with a "public" access modifier meaning that everyone everywhere can access it.

> [Oracle Documentation](http://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html) :
> A class may be declared with the modifier public, in which case that class is visible to all classes everywhere. If a class has no modifier (the default, also known as package-private), it is visible only within its own package.

**_Solutions :**_
- [x] Either the documentation before the `getLogHeader(String, int)` method needs to be removed, or the scope of the method needs to change.

~~The commentary before both the `getBaseTicsDelta()` method and the `getBaseTics()` should be replaced with a more accurate description, or removed entirely. _Change is unneeded if solutions to (2) are accepted as they end up removing these methods._~~

---

Backwards Compatible :+1:
### **(2) UTC Time**

The [SdlTrace](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java) class contains the following code.

``` java
private static long baseTics = java.lang.System.currentTimeMillis();

static long getBaseTicsDelta() {
    return java.lang.System.currentTimeMillis() - getBaseTics();
}

static long getBaseTics() {
    return baseTics;
}
```

> [Oracle Documentation](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html) :
> Returns the current system time in milliseconds since January 1, 1970 00:00:00 UTC. This method shouldn't be used for measuring timeouts or other elapsed time measurements, as changing the system time can affect the results.

There are several issues with this small amount of code.

First of all, the value of `baseTics` is only determined once so it should have the "final" modifier and follow related naming conventions. If the value is a constant then it is immutable and there is no danger in accessing it statically since it cannot be changed. 

Next, the JavaDoc for `currentTimeMillis()` specifically states not to use it for time measurement, yet that is exactly what it is being used for in this code.

Also, the method `getBaseTicsDelta()` within the libaray is only called to be sent as a parameter to the `encodeTraceMessage(long, Mod, InterfaceActivityDirection, String)` method within the [SdlTrace](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java) class. The timestamp parameter can be calculated within the later private method instead and the former can be deprecated.

Finally, the documentation for `currentTimeMillis()` specifically states that it is **not** to be used for determining a time difference but this is exactly what it is being used for. However, the timestamp being put in the trace method is determined from when the static value `baseTics` is first declared (at the start of the program) and when the `getBaseTicsDelta()` method is called. The only noteworthy use for this would be to provide some kind of an ordering for the trace messages through the duration of the program, but regardless it is not promised to be accurate.

**_Solutions :**_
- [x] Add the "final" modifier to the `baseTics` variable and rename to `BASE_TICS` to follow proper naming convention.
- [x] Remove the "private" scope of `baseTics` (or `BASE_TICS`) to match the "package-private" scope of it's accessor method and remove the unneeded accessor method `getBaseTics()`. _This will not cause a backwards compatibility problem because it is not used anywhere else in the package._
- [x] Remove the `getBaseTicsDelta()` method and the `encodeTraceMessage(long, Mod, InterfaceActivityDirection, String)` and replace it with a functionally equivalent method overload `encodeTraceMessage(Mod, InterfaceActivityDirection, String)` that calculates the timestamp within. _Both removals are backwards compatible since the former is not used anywhere in the package and latter scope is private._
- [ ] Either document the potential innaccuracy of the timestamp contained in the encoded trace message or find and implement a more accurate solution.

---

Backwards Compatible :+1:
### **(3) Deprecation**

`@SuppressWarnings("deprecation")` appears before the `getLogHeader(String, int)` method towards the bottom of the [SdlTrace](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java) class.

It calls the deprecated `Timestamp.toGMTString()`, which is not a necessary call and a suggested solution was posted in the comments above this deprecation but not implemented.

**_Solutions :**_
- [x] Replace the block of time calculations with the suggested solution and remove the `@SuppressWarnings("deprecation")` tag from the method.

---

Backwards Compatible :-1:
### **(4) XML Tags**

(Concerning the `getLogHeader(String, int)` method).

Although I have not found and do not believe there is a standard convention for XML tag names the project should at least stay consistent. For all except the `<SmartDeviceLinktraceroot>` tag exclusively lowercase letters are used regardless of if it is comprised of multiple words. This tag not only doesn't conform to the rest, but it doesn't even follow camel case.

On top of this, it seems that the XML header contains errors.

``` java
"<logs>" + "<info>"
...
"</info>" + "<msgs>");
```

The `<info>` tag is properly closed, but the `<logs>` tag is not. Perhaps `<msgs>` was supposed to be `</logs>`? Either way this encapsulation is unneeded and both the `<logs>` and the `<msgs>` tags should been removed. This would be a breaking change, but the structure is already faulty.

**_Solutions :**_
- [x] Rename the nonconformist tag to `<sdltraceroot>` and `</sdltraceroot>` respectively.
- [x] Remove the `<logs>` and `<msgs>` tags from the XML header.

**Note :** This is not a backwards compatible change. This method is not used within the library project itself, so wherever developers use it _may_ need to change _if_ they are extracting the data from the XML.

---

Backwards Compatible :+1:
### **(5) String vs. StringBuilder**

(Concerning the `getLogHeader(String, int)` method).

This method is incredibly inconsistent with how it handles building the XML header. Between concatenating Strings, using the StringBuilder, and concatenating Strings within the calls to the StringBuilder it is all quite a mess.

**_Solutions :**_
- [x] Either choose to concatenate all of the string information for uniformity, or _(the more strongly suggested solution)_ use the StringBuilder class as intended and remove the concatenation entirely.

---

Backwards Compatible :-1:
### **(6) Method Purpose**

(Concerning the `getLogHeader(String, int)` method).

Both release and debug build information is retrieved in order to construct the XML header. For example, the `Build.VERSION.RELEASE` is called and shortly after the `Debug.getNativeHeapFreeSize()` is called. 

There is documentation for the Build class regarding version information the specifically states that the version is incremented for every [official platform release](http://developer.android.com/reference/android/os/Build.VERSION_CODES.html).

No where can I find it stated that the Debug or Build class information would be inaccessible in either a debug or release version of the application, but the intended usage of the `getLogHeader(String, int)` method is not incredibly clear. The Debug class is primarily used to log information to the native Android log tool, but the information provided in the header is encoded in XML and in some places in Base64 so logging as such doesn't make much sense.

**_Solutions :**_
- [ ] Document what the intended purpose of the `getLogHeader(String, int)` method and how it should be used by developers. _If it should only be used for logging messages in debug mode then add an internal check in the method to verify the state of the application._

---

Backwards Compatible :+1:
### **(7) Unneeded Methods**

The `getProtocolFrameType(FrameType)`, `getProtocolSessionType(SessionType)`, and `interfaceActivityDirectionToString(InterfaceActivityDirection)` methods are unecessary and leave a lot of room for mistakes if a new FrameType or SessionType is added to the enum but this method is not updated. Converting the enum to a string can be done without so much work.

**_Solutions :**_
- [x] Remove the methods and instead use the enums actual `toString()` for string conversion.

---
#### Other Questions
1. Why does the information between the `<host>` and the `<osv>` tags in the `getLogHeader(String, int)` method need to be encoded? The information isn't exactly private or Android would require an application permission to be requested so why would it need to be protected?
2. Can someone explain the following comment more clearly? It appears after several instances of encoding log information.

``` java
// Base64 only available in 2.2, when SmartDeviceLink base is 2.2 use: return Base64.encodeToString(data.getBytes(), Base64.DEFAULT);
```

Why would Base64 only be available in 2.2? I can call it just fine now with the same code in development 4.0 so does this actually mean SDL >= 2.2?

---
#### General Corrections
- [ ] Add or update JavaDoc information in SdlTrace.
- [ ] Add or update useful inline comments in SdlTrace.
- [x] Remove trivial comments from class.
- [ ] If needed, refactor variable or method names to be meaningful.
- [x] Consolidate the `getSmartDeviceLinkTraceRoot(String, int)` method into the `getLogHeader(String, int)` method.
- [ ] If the logging consolidation branch (#190) is merged then proper trace logging should be implemented instead of the debug log calls currently in place.
- [x] If the Base64 encoding is still needed, remove the unnecessary encapsulation present in the`B64EncodeForXML(String)` method.
- [x] Clean up the nested try/catch blocks in `writeXmlTraceMessage(String)`.
- [ ] On the unit test branch verify that the existing log event methods do not cause NullPointerExceptions or ArrayIndexOutOfBoundsExceptions by invalid or conflicting offset and length values, create tests if none exists.

**Comment by joeljfischer** [comment]
@joeygrover @bilal-alsharifi can this be reviewed an potentially closed or a card opened for it?

**Comment by joeygrover** [comment]
Closed for being stale.
