### ISSUE TITLE
SdlProxyBase.dispose() sometimes deadlocks

### ISSUE THREAD

**Issue by pbulka** [smartdevicelink/sdl_java_suite#570]
We have noticed that sometimes while disconnecting from a TDK headunit using USB, the call to SdlProxyBase.dispose() never returns.  A thread in SdlConnection becomes deadlocked with another thread in SdlProxyBase (see PROTOCOL_REFERENCE_LOCK and CONNECTION_REFERENCE_LOCK)

This was first discovered on our own app, but it is also reproducible on the latest version 4.3 of the hello_sdl_android sample.
Tested on samsung galaxy note 4 (android 6.0.1) and galaxy S8 (android 7)

**Comment by Tnnnguyen** [comment]
Question: did this bug happen before 4.3?

**Comment by Tnnnguyen** [comment]
What is the frequency of this bug?
What are the steps to reproduce it?
What is the behavior of the device / head unit when this happened?
I will try to reproduce it, but it's much better if we have info from the developer to confirm.

**Comment by pbulka** [comment]
We started noticing this problem in our app because the lockscreen on the phone is programmed to close after disposing of the proxy.  Basically what happens is our app freezes with the lockscreen open when we disconnect from the TDK, and the only thing that can be done is to kill our app.  The TDK continues to work normally.
I would say the frequency is about 25%

Steps to reproduce in the latest hello_sdl_android with a small change in the code are as follows:
- in function disposeSyncProxy(), move the line "LockScreenActivity.updateLockScreenStatus(LockScreenStatus.OFF);"
to the end of the function
- compile and install APK

Successfully connect to the TDK, the lockscreen appears on the phone, then disconnect from TDK
Once disconnected, if the lockscreen disappears, repeat the above step until the lockscreen does not disappear.  proxy.dispose() will be blocked

Hope this helps, I cannot confirm that this was occurring also before 4.3

**Comment by pbulka** [comment]
We discovered what was causing this problem.

SdlProxyALM.dispose(), or other proxy related functions should not be directly called in onProxyClosed when the proxy was constructed with callbackToUIThread set to false

**Comment by tvkanters** [comment]
I have also been able to reproduce this with `callbackToUIThread = true`.

**Comment by theresalech** [comment]
This class has been deprecated and will be removed in the next major release (October, 2020).  Therefore, we do not plan on creating a fix for this issue.
