### ISSUE TITLE
default appHMIType is null

### ISSUE THREAD

**Issue by poborin** [smartdevicelink/sdl_java_suite#608]
there is a `private Vector<AppHMIType> _appType = null;` in both SdlProxyBuilder and SdlProxyBase. Meanwhile the application must have a default HMI type unless other is required. As the AppHMIType is enum we have a limited set of options. Thus, I would recommend either initialise a vector with default value or use a bitmap masked enum instead of vector.

**Comment by RHenigan** [comment]
`SdlProxyBuilder` and `SdlProxyBase` are going away in Release 5.0.0, In `BaseSdlManager`, which is used going forward, when the SdlManager is built if the hmiType is null it is then assigned `HMIType.DEFAULT`.
