### ISSUE TITLE
SDL Router fails silently when not able to advertise BT service

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_java_suite#664]
### Bug Report
When SDL Router service tries to set up an BT RFCOMM service but either there are no available RFCOMM channels or there are no available service records then the service silently fails to advertise leaving the user wondering why SDL apps don't work.

##### Reproduction Steps
1. Run several non-SDL BT apps
2. Run or restart SDL router service
3. Connect to HU
4. If SDL status icon appears then retry adding more non-SDL BT apps in step 1.

##### Expected Behavior
App containing SDL router service should show an alert to the user that there are too many BT apps running.  Expecting notification from SDL router service to containing app, either through binding or broadcast, letting app know it should show an alert.

##### Observed Behavior
No SDL status icon but no alert letting user know that SDL router couldn't start BT server socket.

##### OS & Version Information
* Android Version: various
* SDL Android Version: 4.4.0

##### Samples From Apps That Show Alerts

![screenshot_2017-08-02-12-20-55](https://user-images.githubusercontent.com/17129766/34268740-b81f153a-e636-11e7-9a0b-f8d063d80dd4.png)
![screenshot_20170830-180803](https://user-images.githubusercontent.com/17129766/34268741-b82f5ae4-e636-11e7-94c0-6416c822ac32.png)

**Comment by joeygrover** [comment]
Fixed with #1132.
