### ISSUE TITLE
Router Service Swapping Ability

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_java_suite#665]
# Router Service Swap

## Introduction
- We are aware that for certain apps installation flow, we end up with a device that has **_n SDL enabled multiplexing apps running n BT channels_**.
- This is because the running router service is not trusted by any other apps. As this service can practically keep running silently in the background (and therefore, hosting), there is no easy way to get out of this situation.
- One way to get out of it is to force kill the hosting app (not normal, frequent activity from a normal user stand point). But even then there is a possibility that another none-trusted router service takes place next and we are back to square one.
- We will attempt to fix that issue here without the need to share trusted list between apps.
- All we need is one head unit resets within certain time elapse after the last trusted list download.
- The key to the solution is to find a time window where the trusted list is considered reasonably best and newest, coupled with the ability to validate apps using different security settings.
 
### Concepts & Safe Assumptions:

The proposed solution is taking advantage of a few points here:
1. We can kill the running router service and start another (better as in being trusted by more apps) one when transport is disconnected and the new service will be silently listening for RFCOMM channel.

2. The validation process is the same for all apps, meaning given a package name (the app being validated) and a security setting for a validation run, all apps will agree on if that package is trusted or not.

3. Any app can validate any other package (other installed apps), including itself, using any level of security: HIGH, MEDIUM, LOW.

4. The last downloaded time of the trusted list is easily retrieved.

5. **_Elapse time_**: elapse time refers to the amount of time that has passed since the last trusted list download until now. If the app (the running router service) just successfully downloads the trusted list and one second later, the car turned off, we go to exit foreground; **_this one second elapse time can be considered best_**. 

6. **_Reasonable elapse time_**: base on number 5 above, the smaller the elapse time, the better chance the trusted list is the latest. Then a reasonable elapse time of 1 (one) day is probably the choice here as the code will attempt to swap at the very next time the head unit is turned off after the list has been downloaded in the same run. This is because it's extremely unlikely that a car is started and driven for more than 24 hours straight. _Of course, there is no guarantee that all apps will have the same trusted list at any time. This is the current behavior as different apps have different times of download and different periodic refresh rate (7 days for HIGH & MEDIUM, 30 days for LOW security settings)._ 

7. The one luxury we have is that the service will be running in the background after the head unit is turned off (transport disconnected, foreground exited) so we have the context available to us and time is not an issue. The code will just run in the background and if it deems, **_in a safe manner_**, that swapping can be done, it will make the swap.

### Algorithm Description:
1. The algorithm is run during exit foreground flow. 
2. If the elapse time is more than the preset reasonable amount, nothing else happens. Normal foreground exit takes place.
3. Only if when elapse time is less than the preset reasonable amount, the running service will determine its trust worthy level and depending on the level, it will bubble up a better (more trust worthy as in being trusted by more apps) service if if finds any. In any case, the new router service is guaranteed to be better than the currently running router service. If no other router service is better, no swapping will take place.
4. If self validates (a modified form of validation, using the exact logic, but skipping certain unnecessary parts, more elaboration in Modifications section) and  security level is HIGH: If the running service is validated at HIGH security level, there is no need to swap.
5. If not, we are potentially operating at MEDIUM level: if there is any other app that validates at HIGH security level: swap
6. If not, we are potentially operating at LOW level: if there is any other app that validates at MEDIUM security level: swap
7. If not, we are potentially operating at OFF level: if there is any other app that validates at LOW security level: swap. 
8. If not, all apps are operating at OFF level: no swap

### RouterServiceValidator modifications, for swapping validation only, normal validation during connection stays the same
1. The validation code from `RouterServiceValidator.java` currently uses an internally saved security setting; we can modify its `validate()` method to bypass this internal setting and make the method use the security setting we want.
2. The `validate()` method currently also has code to ensure the package (service being validated) has a service running. For the purpose of the swapping validation, we can also bypass this part.
3. The `validate()` method currently also attempts to wake up the router service at the end when it returns false; we can again skip this part during swapping validation.
4. The `validate()` method currently uses the package name from its own context; we can modify to have it use the supplied package name during swapping validation.

**_Note_**: to ensure all apps agree on the validation process, it's important that no logic is changed. We only skip certain part that is not needed during swapping validation. The other change is the use of the supplied security setting bit instead of using the internally saved setting.

### Router Swapping
...

## Drawbacks And Other Considerations

1. Other apps may miss the reasonably latest trusted list that this app uses in the algorithm (so there can be differences between this app's trusted list and other app's trusted lists):
Currently this is also happening in the library; they will just have to wait on their next download to sync with the rest.

2. What if an app is immediately removed from the trusted list on server side after it was validated and promoted to run in the algorithm?
    - Apps that do not update their trusted list (and thus do not see this new removal) still use the promoted service. This is already happening in the library when the current hosting router service is removed from the trusted list. They will just have to wait on their next download to sync with the rest.
    - Apps that did catch this update will revert to BT legacy. This is also happening in the library.
    - **_The (better) difference is that the running router service has a chance to run the algorithm and promote better app_**. We can also improve the chance for the algorithm to run by sending a broadcast that contains the download time at any time any app downloads the trusted list. Only the running service will register the receiver for this broadcast and receive the download time. This will make the algorithm run more frequently and we have nothing to lose and except code that runs on the background without any user engagement.

3. What if a "better", as in more trustworthy, app is added to the trusted list on the server side after we promoted the current best router service?
    - Apps will have to wait until their next download time. This is already happening in the library.
    - We already have the current next to best router service and in many cases, it may as well be the best (validated with HIGH security setting) app.
    - When the algorithm gets a chance to run next, it will promote that newly added "better" service if it is "better" than the current host.

4. The algorithm can run more than once if the head unit is reset more than once within the reasonable elapse time:
We don't lose anything except code that runs silently in the background. But we can put in safeguard to make sure the algorithm only run once within one reasonable elapse time.

5. What if there is failure during trusted list download (network, server failure for example):
No trusted list is downloaded and the download time stamp is not updated. This is already happening in the library. The elapse time will more than likely be too long for the algorithm to start.
Apps will have to wait until their next download.

In the long run, we will end up with the best router service. If there is any chance this hosting app is removed (or added to black list as checked by verifyVersion method) from the trusted list, the algorithm will correct the situation and again, we will end up with the best router service.

**Comment by joeygrover** [comment]
Requires an evolution proposal and therefore will be closed until one is entered and accepted.
