### ISSUE TITLE
[SDL 0179] Pixel density and Scale

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#804]
Proposal: [Pixel density and Scale](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0179-pixel-density-and-scale.md)

> This proposal is about adding parameters to `VideoStreamingCapabilities` for pixel density and scale.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/526

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0179 Revisions - Pixel Density and Scale](https://github.com/smartdevicelink/sdl_evolution/issues/808). Revisions include adding `minvalue`s of `0` for `pixelsPerInch` and `diagonalScreenSize` as well as a `minvalue` of `1` and `maxvalue`10` for `scale` parameters in the `VideoStreamingCapability`. Please reference issue and proposal markdown file for more details.

**Comment by BrettyWhite** [comment]
Closed with #1119
