### ISSUE TITLE
[SDL 0186] Template Titles

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_java_suite#818]
Proposal: [Template Titles](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0186-template-titles.md)

> Templates should have the capability to have a title to help orient the user in the UI.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/542

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions.  The revisions will include adding the parameter to the `Show` RPC and also renaming the parameter to something more specific, such as `TemplateTitle`. 
> The proposal .md file was updated to reflect these revisions on 7/18/18.

**Comment by theresalech** [comment]
Proposal markdown file has been updated per the revisions included in accepted Evolution Proposal [SDL 0186 Revisions - Template Titles](https://github.com/smartdevicelink/sdl_evolution/issues/783).  These changes include adding a new `TextFieldName` value and permitting the `templateTitle` to be altered by setting it to an empty string.  Please reference issue and markdown file for more details.

**Comment by BrettyWhite** [comment]
Closed via #1111
