### ISSUE TITLE
[SDL 0200] - Removing URL Parameter Max Length

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_java_suite#906]
Proposal: [Removing URL Parameter Max Length](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0200-Removing-URL-Param-Max-Length.md)

> This proposal is to remove maximum length attribute for URL strings provided to OnSystemRequest, StartStream and StartAudioStream and let the URL strings be of any length permissible by the system architecture.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/603

Steering Committee Decision:

> The Steering Committee accepted this proposal on 10/16/2018. The following was discussed in the Steering Committee meeting on 2018-10-16, with regards to this proposal: Although there are no iOS or Android limitations over the size and length of URLs, excessively long ones may take a long time to create / parse, and extensive data should be sent via a method that is not a URL (e.g. JSON in the bulk data).
Lastly, while it's understood that SDLC members cannot share all use cases for features publicly, it was acknowledged that in the future, when requesting specific features, it is helpful to have real world examples to better understand the reasoning and planned implementation for the requested changes.

**Comment by kostyaBoss** [comment]
@theresalech While checking the codebase and tests, it was discovered that for implementing this proposal no additional code changes in sdl_java_suite are required

**Comment by theresalech** [comment]
@kostyaBoss, we understand that code changes are not required.  However, we should still add unit tests for this feature.  Can you please provide?  Thank you!
