### ISSUE TITLE
Secondary transport is not set up as soon as its available

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_java_suite#919]
### Bug Report
The secondary transport is not set up as soon as the proxy is notified of available transport types.  The accepted multiple transport proposal (linked below) indicates that "Proxy should set up Secondary Transport as soon as it is notified of available transport types for Secondary Transport and information that is necessary to set up the transport becomes available."
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0141-multiple-transports.md

It is understood that best practices indicate that wifi sockets should only be opened and used when required to reduce network battery drain as indicated in the link below, however this issue is being reported because the current Android proxy implementation does not follow the accepted proposal above.
https://developer.android.com/topic/performance/power/network/

##### Reproduction Steps
Download and build the Android 4.7.1 proxy and build the SdlStreaming sample application.
Register the sample application with SDL Core, ensure SDL Core logs have been turned on.
Via SDL Core logs take note that the secondary transport is only registered just before the application starts a nav or pcm service (as opposed to when the application initially registered).

##### Expected Behavior
The secondary transport will be registered after its notified of available transport types (based on accepted proposal).

##### Observed Behavior
The secondary transport is only registered just before the application starts a nav or pcm service.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.7.1
* Testing Against: SDL Core 5.0.0, WebHMI, & Proprietary Head Unit Implementation

##### Test Case, Sample Code, and / or Example App
SdlStreaming

**Comment by lauratonwe** [comment]
@shoamano83 can you please add your email dialogue with the project maintainer (Joey) so that we have all information relating to this bug in one place?  Also if there is a PR for a fix can you please add a link to it here as well?  

Thanks so much.

Laura

**Comment by joeygrover** [comment]
I will be recommending this bought in as an item for the steering committee review, because of this no PR will be reviewed prior to comments from the SDLC members. If the SDLC members agree that it should be connected as soon as available due to the proposal stating the included text, I will be entering a proposal to change that behavior as I strongly believe this flow is a bad practice and makes the library worse.

**Comment by lauratonwe** [comment]
@joeygrover we agree and are planning on bringing this up during the sdlc meeting on the 13th as a walk in item.  We are preparing a write up for Jordyn and will get it to her before Friday so she can add it to the agenda.  Thanks :)

**Comment by shoamano83** [comment]
Hi Laura and Joey, I'm copying our dialog over e-mails.

On Thu, Nov 1, 2018 at 4:23 AM Sho Amano <samano@xevo.com> wrote:

> I'm working with Ford team to investigate an issue regarding sequence of Wi-Fi secondary
> transport registration. I have created a fix for it, but before submitting a PR I would like to
> discuss with you. Since it's likely a sequence change, I want to make sure it will align with
> your thought.
>  
> I would appreciate if you could go through the descriptions of our issue and the change. If you
> have any feedback on it - whether it's acceptable or you have any concerns, please kindly share.
> 
> ## Summary of the issue
> 
> The proposal of multiple transports (https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0141-multiple-transports.md) states:
> 
> > Starting Secondary Transport
> >
> > Proxy should set up Secondary Transport as soon as it is notified of available transport types for Secondary Transport and information that is necessary to set up the transport becomes available.
> 
> However, Android library (as of v4.7.1) doesn't set up secondary transport when it receives
> Transport Event Update frame with valid IP address and port number. Instead, it initiates
> the secondary transport when a NAV or PCM service is requested:
> https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/protocol/SdlProtocol.java#L782
> So the behavior doesn't align with the proposal.
> 
> ## Why it's a problem
> 
> Ford's HMI limits a streaming app to work only with USB transport or Wi-Fi secondary transport. For this purpose, it uses
> the registration state of TCP secondary transport. When the secondary transport isn't registered, HMI doesn't allow
> the app to go into FULL level.
>
> Unfortunately this design doesn't work well with current Android library. Since HMI doesn't make the app FULL, the app
> will not initiate streaming, and it won't call startRemoteDisplayStream(). So NAV/PCM services won't be started, which
> in turn will not initiate secondary transport connection/registration.
> 
> ## Solution
> 
> My solution is to add a trigger of TCP transport connection and secondary transport registration after receiving
> Transport Event Update frame. This behavior should align with the proposal, and also with iOS library.
> 
> You can find my fix here:
> https://github.com/XevoInc/sdl_android/tree/fix/secondary_transport_sequence_3
> 
> I tried to make the change as minimum as possible so that hopefully it won’t break anything.
> 
> The only concern is that this is a change in sequence. If there is an app / a HMI that relies on current sequence,
> this change may give negative impact. If you know any background of current sequence, or have any concerns,
> please kindly share.


Joey replied:

> Hi Sho,
> 
> I understand the concern. The issue is that all apps will try to open a TCP connection regardless of one ever being used or not. This is very irresponsible from a coding and resource perspective; the library would create and maintain a TCP connection regardless of any intention of ever being used. The sequence works with the open source Core library as well so it has proven to be successful with no limitations. Since the library itself is already in production I would recommend investigating a sequence change on Ford's software. It seems as though an arbitrary sequence that can be corrected on the hardware with limited impact where changing the library will have a resource and processing power impact which looks bad to developers.


On Fri, Nov 2, 2018 at 2:29 AM Sho Amano <samano@xevo.com> wrote:

> Hi Joey and Markos,
> 
> Thank you for your feedback Joey.
> I do not own Ford's head unit code so I must ask Ford team whether such change in
> head unit is acceptable. Markos, do you have a good idea on how to change the
> sequence on head unit?
>  
> Actually I do understand Joey’s concern that with my change, even a non-streaming
> app will set up a TCP secondary transport which is waste of resources. iOS library has
> less impact, as it sets up TCP transport only when the app is in foreground. All the
> other apps in background don't set up it.
>  
> If that's the major concern, then an alternative is to trigger TCP secondary transport
> connection and registration with Transport Event Update frame only when
> _requiresHighBandwidth_ is true. Therefore the transport will be established with
> streaming apps only. I think this also comes with a small benefit that secondary
> transport will be set up prior to the app being FULL, so streaming would be started
> immediately once the app would get FULL and be shown.
> To Joey and Markos, do you have thoughts on this?

Joey replied:

> Hi Sho,
> 
> I think the second solution is better, but it will still connect over a transport with no guarantee that it will be used. For example, a user connecting over bluetooth and then TCP automatically every time they get into the car even though most of the time they will likely not need the video streaming service. This will drain battery as well especially if the user gets in and out of their car a lot, or even when running errands.  
> 
> Also, the requiresHighBandwdith flag can still be set to false and still intend to stream. The flag essentially allows developers to create a low bandwidth implementation and a high bandwidth one of they wish. For example, simple turn by turn when only low bandwidth is available, and then do actual streaming when high is available. If a developer doesn't want to do that, they set the flag to true and will only register when a high bandwidth is available (either already connected or can be connected). Also we haven't really noticed any performance issues in terms of the time taken to wait until a streaming service wishes to be started instead of automatically when info is available.

**Comment by joeygrover** [comment]
Closed as a result of https://github.com/smartdevicelink/sdl_evolution/pull/628
