### ISSUE TITLE
VR commands created by Lib when its not provided by App

### ISSUE THREAD

**Issue by ashwink11** [smartdevicelink/sdl_java_suite#941]
### Bug Report
VR commands created by Lib when its not provided by App

##### Reproduction Steps
1. Register Hello SDL Android App
2. Create Choice without VR commands
3. Send Create Interaction Choice Set

##### Expected Behavior
Lib should not create VR commands when its not provided by App

##### Observed Behavior
Lib creating VR commands using choice ID and sending it.

##### OS & Version Information
* Android Version: 9
* SDL Android Version: 4.7.2
* Testing Against: SYNC

##### Test Case, Sample Code, and / or Example App

Did not observe this behavior in iOS SDL Library

**Comment by joeygrover** [comment]
The current library builds RPCs in accordance to the negotiated RPC spec version so that developers do not have to worry about it themselves. This PR would then break that ability by circumventing the negotiated RPC spec allowing for bad actors going against the RPC spec.

**Comment by BrettyWhite** [comment]
Closed with the creation of the Choice set manager #1080
