### ISSUE TITLE
Some apps don't get START_ROUTER_SERVICE_ACTION broadcast from SdlRouterService

### ISSUE THREAD

**Issue by shiniwat** [smartdevicelink/sdl_java_suite#958]
### Bug Report
Some apps don't get START_ROUTER_SERVICE_ACTION broadcast from SdlRouterService, which caused the apps not getting registered.

##### Reproduction Steps
(prerequisite) 0. Run SDLCore, HMI on HU. Run a couple of SDL apps (e.g. hello_sdl_android, etc) on Android device. Make sure the apps get registered and appeared on HU.
1. Remove some app that does not act as the RouterService (e.g. helllo_sdl_android) from recent list. The app will be killed.
2. Relaunch the app (e.g. hello_sdl_android)

##### Expected Behavior
The app gets registered and appear on HU.

##### Observed Behavior
The app does not get registered.

##### OS & Version Information
* Android Version: Android 9.0 on Pixel
* SDL Android Version: commit 7d329a17dc95fe16df557827fead48cb4caa79a2 at develop branch
* Testing Against: SDL Core 4.5 + HMI running on our development environment.

##### Test Case, Sample Code, and / or Example App
I will submit the possible PR with UnitTest later.

**Comment by joeygrover** [comment]
Closing as a stale issue.
